--		Weapon components fall into two groups: "model-specific" and "shared". "Shared" are divided into "shortarm", "longarm",
--		"shotgun" and "melee_blade". 
--		Be careful, the "FRAME_VERTDATA" component breaks colors for other components. You must remove it for the other
--		components to work.
--		
--		
--		
--		
--		
--		Example. Create weapon object, load weapon asset (with native 0x72D4CB5DB927009C) if your ped dont equip this type of weapon yet, and then :
--		
--		
--		local entity_id = ENTITY_ID_HERE   --  WEAPON_REVOLVER_CATTLEMAN object id here or ped with equipped WEAPON_REVOLVER_CATTLEMAN
--		local weapon_object_model_hash = GetHashKey("WEAPON_REVOLVER_CATTLEMAN")
--		local weapon_component_hash1 = GetHashKey("COMPONENT_REVOLVER_CATTLEMAN_BARREL_LONG")    		-- model-specific weapon component
--		local weapon_component_hash2 = GetHashKey("COMPONENT_SHORTARM_BARREL_MATERIAL_7")				-- shared weapon component
--		local weapon_component_hash3 = GetHashKey("COMPONENT_SHORTARM_BARREL_ENGRAVING_2")				-- shared weapon component
--		local weapon_component_hash4 = GetHashKey("COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_3")		-- shared weapon component
--		
--		local function apply_weapon_component(weapon_component_hash)
--			local weapon_component_model_hash = Citizen.InvokeNative(0x59DE03442B6C9598,weapon_component_hash)  -- GetWeaponComponentTypeModel
--			if weapon_component_model_hash and weapon_component_model_hash ~= 0 then
--				RequestModel(weapon_component_model_hash)
--				local i = 0
--				while not HasModelLoaded(weapon_component_model_hash) and i <= 300 do
--					i = i + 1
--					Citizen.Wait(0)
--				end
--				if HasModelLoaded(weapon_component_model_hash) then
--					Citizen.InvokeNative(0x74C9090FDD1BB48E,entity_id,weapon_component_hash, weapon_object_model_hash, true)  -- GiveWeaponComponentToEntity
--					SetModelAsNoLongerNeeded(weapon_component_model_hash)
--				end
--			end	
--		end
--		
--		apply_weapon_component(weapon_component_hash1)
--		apply_weapon_component(weapon_component_hash2)
--		apply_weapon_component(weapon_component_hash3)
--		apply_weapon_component(weapon_component_hash4)
--		
--		
--		
--		
--		
--		To remove weapon component:
--		
--		if Citizen.InvokeNative(0x76A18844E743BF91,entity_id, GetHashKey("COMPONENT_SHORTARM_BARREL_ENGRAVING_2") ) then  -- HasWeaponGotWeaponComponent
--		  	Citizen.InvokeNative(0xF7D82B0D66777611,entity_id, GetHashKey("COMPONENT_SHORTARM_BARREL_ENGRAVING_2") )   -- RemoveWeaponComponentFromWeaponObject
--		end
--			
--		
--		
--		
--		
--		local weapon__to__shared_group_of_components = {
--			["WEAPON_BOW"]                           = {},
--			["WEAPON_FISHINGROD"]                    = {},
--			["WEAPON_KIT_BINOCULARS"]                = {},
--			["WEAPON_KIT_CAMERA"]                    = {},
--			["WEAPON_KIT_METAL_DETECTOR"]            = {},
--			["WEAPON_LASSO"]                         = {},
--			["WEAPON_MELEE_CLEAVER"]                 = {"MELEE_BLADE",},
--			["WEAPON_MELEE_DAVY_LANTERN"]            = {},
--			["WEAPON_MELEE_HATCHET"]                 = {"MELEE_BLADE",},
--			["WEAPON_MELEE_HATCHET_DOUBLE_BIT"]      = {"MELEE_BLADE",},
--			["WEAPON_MELEE_HATCHET_HUNTER"]          = {"MELEE_BLADE",},
--			["WEAPON_MELEE_KNIFE"]                   = {"MELEE_BLADE",},
--			["WEAPON_MELEE_KNIFE_JAWBONE"]           = {"MELEE_BLADE",},
--			["WEAPON_MELEE_KNIFE_SEAN"]              = {"MELEE_BLADE",},
--			["WEAPON_MELEE_LANTERN_ELECTRIC"]        = {},
--			["WEAPON_MELEE_MACHETE"]                 = {"MELEE_BLADE",},
--			["WEAPON_MELEE_TORCH"]                   = {},
--			["WEAPON_PISTOL_M1899"]                  = {"SHORTARM",},
--			["WEAPON_PISTOL_MAUSER"]                 = {"SHORTARM",},
--			["WEAPON_PISTOL_SEMIAUTO"]               = {"SHORTARM",},
--			["WEAPON_PISTOL_VOLCANIC"]               = {"SHORTARM",},
--			["WEAPON_REPEATER_CARBINE"]              = {"LONGARM",},
--			["WEAPON_REPEATER_EVANS"]                = {"LONGARM",},
--			["WEAPON_REPEATER_HENRY"]                = {"LONGARM",},
--			["WEAPON_REPEATER_WINCHESTER"]           = {"LONGARM",},
--			["WEAPON_REVOLVER_CATTLEMAN"]            = {"SHORTARM",},
--			["WEAPON_REVOLVER_CATTLEMAN_DUALWIELD"]  = {"SHORTARM",},
--			["WEAPON_REVOLVER_CATTLEMAN_MEXICAN"]    = {"SHORTARM",},
--			["WEAPON_REVOLVER_DOUBLEACTION"]         = {"SHORTARM",},
--			["WEAPON_REVOLVER_DOUBLEACTION_GAMBLER"] = {"SHORTARM",},
--			["WEAPON_REVOLVER_LEMAT"]                = {"SHORTARM",},
--			["WEAPON_REVOLVER_NAVY_CROSSOVER"]       = {"SHORTARM",},
--			["WEAPON_REVOLVER_SCHOFIELD"]            = {"SHORTARM",},
--			["WEAPON_RIFLE_BOLTACTION"]              = {"LONGARM",},
--			["WEAPON_RIFLE_SPRINGFIELD"]             = {"LONGARM",},
--			["WEAPON_RIFLE_VARMINT"]                 = {"LONGARM",},
--			["WEAPON_SHOTGUN_DOUBLEBARREL"]          = {"LONGARM",},
--			["WEAPON_SHOTGUN_DOUBLEBARREL_EXOTIC"]   = {"LONGARM",},
--			["WEAPON_SHOTGUN_FOLDING"]               = {"LONGARM","SHOTGUN",},
--			["WEAPON_SHOTGUN_PUMP"]                  = {"LONGARM","SHOTGUN",},
--			["WEAPON_SHOTGUN_REPEATING"]             = {"LONGARM","SHOTGUN",},
--			["WEAPON_SHOTGUN_SAWEDOFF"]              = {"SHORTARM","SHOTGUN",},
--			["WEAPON_SHOTGUN_SEMIAUTO"]              = {"LONGARM","SHOTGUN",},
--			["WEAPON_SNIPERRIFLE_CARCANO"]           = {"LONGARM",},
--			["WEAPON_SNIPERRIFLE_ROLLINGBLOCK"]      = {"LONGARM",},
--			["WEAPON_THROWN_BOLAS_HAWKMOTH"]         = {},
--			["WEAPON_THROWN_BOLAS_INTERTWINED"]      = {},
--			["WEAPON_THROWN_BOLAS_IRONSPIKED"]       = {},
--			["WEAPON_THROWN_DYNAMITE"]               = {},
--			["WEAPON_THROWN_MOLOTOV"]                = {},
--			["WEAPON_THROWN_THROWING_KNIVES"]        = {},
--			["WEAPON_THROWN_TOMAHAWK"]               = {},
--			["WEAPON_THROWN_TOMAHAWK_ANCIENT"]       = {},
--			["WEAPON_KIT_CAMERA_ADVANCED"]           = {},
--			["WEAPON_MELEE_MACHETE_HORROR"]          = {"MELEE_BLADE",},
--			["WEAPON_BOW_IMPROVED"]                  = {},
--			["WEAPON_RIFLE_ELEPHANT"]                = {"LONGARM",},
--			["WEAPON_REVOLVER_NAVY"]                 = {"SHORTARM",},
--			["WEAPON_BOW_IMPROVED_MP"]               = {},
--			["WEAPON_LASSO_REINFORCED"]              = {},
--			["WEAPON_KIT_BINOCULARS_IMPROVED"]       = {},
--			["WEAPON_MELEE_KNIFE_TRADER"]            = {"MELEE_BLADE",},
--			["WEAPON_MELEE_MACHETE_COLLECTOR"]       = {"MELEE_BLADE",},
--			["WEAPON_MOONSHINEJUG_MP"]               = {},
--			["WEAPON_THROWN_BOLAS"]                  = {},
--			["WEAPON_THROWN_POISONBOTTLE"]           = {},
--			["WEAPON_MELEE_KNIFE_HORROR"]            = {"MELEE_BLADE",},
--			["WEAPON_MELEE_KNIFE_RUSTIC"]            = {"MELEE_BLADE",},
--			["WEAPON_MELEE_LANTERN_HALLOWEEN"]       = {},
--		}





local model_specific_components = {

    ["WEAPON_REVOLVER_CATTLEMAN"] = {
        ["BARREL"] = {
          "COMPONENT_REVOLVER_CATTLEMAN_BARREL_SHORT",
          "COMPONENT_REVOLVER_CATTLEMAN_BARREL_LONG",
          "COMPONENT_REVOLVER_CATTLEMAN_BARREL_LEGENDARY",
        },
        ["GRIP"] = {
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP",
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP_PEARL",
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP_EBONY",
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP_IRONWOOD",
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP_GOOD_HONOR",
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP_BURLED",
          "COMPONENT_REVOLVER_CATTLEMAN_GRIP_LEGENDARY",
        },
        ["SIGHT"] = {
          "COMPONENT_REVOLVER_CATTLEMAN_SIGHT_NARROW",
          "COMPONENT_REVOLVER_CATTLEMAN_SIGHT_WIDE",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_SHORTARM_ROLE_ENGRAVING_CATTLEMAN_LEGENDARY",
        },
    },


    ["WEAPON_REVOLVER_DOUBLEACTION"] = {
        ["BARREL"] = {
          "COMPONENT_REVOLVER_DOUBLEACTION_BARREL_SHORT",
          "COMPONENT_REVOLVER_DOUBLEACTION_BARREL_LONG",
        },
        ["GRIP"] = {
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP",
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_EBONY",
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_IRONWOOD",
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_PEARL",
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_BAD_HONOR",
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_REVOLVER_DOUBLEACTION_SIGHT_WIDE",
          "COMPONENT_REVOLVER_DOUBLEACTION_SIGHT_NARROW",
        },
    },




    ["WEAPON_REVOLVER_DOUBLEACTION_EXOTIC"] = {
        ["GRIP"] = {
          "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_EXOTIC",
        },  
    },



    ["WEAPON_REVOLVER_SCHOFIELD"] = {
        ["BARREL"] = {
          "COMPONENT_REVOLVER_SCHOFIELD_BARREL_SHORT",
          "COMPONENT_REVOLVER_SCHOFIELD_BARREL_LONG",
          "COMPONENT_REVOLVER_SCHOFIELD_BARREL_BOUNTY",
        },
        ["GRIP"] = {
          "COMPONENT_REVOLVER_SCHOFIELD_GRIP",
          "COMPONENT_REVOLVER_SCHOFIELD_GRIP_PEARL",
          "COMPONENT_REVOLVER_SCHOFIELD_GRIP_IRONWOOD",
          "COMPONENT_REVOLVER_SCHOFIELD_GRIP_EBONY",
          "COMPONENT_REVOLVER_SCHOFIELD_GRIP_BOUNTY",
          "COMPONENT_REVOLVER_SCHOFIELD_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_REVOLVER_SCHOFIELD_SIGHT_NARROW",
          "COMPONENT_REVOLVER_SCHOFIELD_SIGHT_WIDE",
          "COMPONENT_REVOLVER_SCHOFIELD_SIGHT_BOUNTY",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_SCHOFIELD_BOUNTY",
        },
    },



    ["WEAPON_PISTOL_MAUSER"] = {
        ["BARREL"] = {
          "COMPONENT_PISTOL_MAUSER_BARREL_SHORT",
          "COMPONENT_PISTOL_MAUSER_BARREL_LONG",
          "COMPONENT_PISTOL_MAUSER_BARREL_AZTEC",
        },
        ["GRIP"] = {
          "COMPONENT_PISTOL_MAUSER_GRIP",
          "COMPONENT_PISTOL_MAUSER_GRIP_PEARL",
          "COMPONENT_PISTOL_MAUSER_GRIP_EBONY",
          "COMPONENT_PISTOL_MAUSER_GRIP_IRONWOOD",
          "COMPONENT_PISTOL_MAUSER_GRIP_BURLED",
          "COMPONENT_PISTOL_MAUSER_GRIP_AZTEC",
        },
        ["SIGHT"] = {
          "COMPONENT_PISTOL_MAUSER_SIGHT_NARROW",
          "COMPONENT_PISTOL_MAUSER_SIGHT_WIDE",
        },
        ["CLIP"] = {
          "COMPONENT_PISTOL_MAUSER_CLIP",
          "COMPONENT_PISTOL_MAUSER_CLIP_EMPTY",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_SHORTARM_ROLE_ENGRAVING_MAUSER_AZTEC",
        }
    },



    ["WEAPON_PISTOL_SEMIAUTO"] = {
        ["BARREL"] = {
          "COMPONENT_PISTOL_SEMIAUTO_BARREL_SHORT",
          "COMPONENT_PISTOL_SEMIAUTO_BARREL_LONG",
        },
        ["GRIP"] = {
          "COMPONENT_PISTOL_SEMIAUTO_GRIP",
          "COMPONENT_PISTOL_SEMIAUTO_GRIP_PEARL",
          "COMPONENT_PISTOL_SEMIAUTO_GRIP_IRONWOOD",
          "COMPONENT_PISTOL_SEMIAUTO_GRIP_EBONY",
          "COMPONENT_PISTOL_SEMIAUTO_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_PISTOL_SEMIAUTO_SIGHT_NARROW",
          "COMPONENT_PISTOL_SEMIAUTO_SIGHT_WIDE",
        },
        ["CLIP"] = {
          "COMPONENT_PISTOL_SEMIAUTO_CLIP",
        },
    },



    ["WEAPON_PISTOL_VOLCANIC"] = {
        ["BARREL"] = {
          "COMPONENT_PISTOL_VOLCANIC_BARREL_SHORT",
          "COMPONENT_PISTOL_VOLCANIC_BARREL_LONG",
          "COMPONENT_PISTOL_VOLCANIC_BARREL_COLLECTOR",
        },
        ["GRIP"] = {
          "COMPONENT_PISTOL_VOLCANIC_GRIP",
          "COMPONENT_PISTOL_VOLCANIC_GRIP_PEARL",
          "COMPONENT_PISTOL_VOLCANIC_GRIP_EBONY",
          "COMPONENT_PISTOL_VOLCANIC_GRIP_IRONWOOD",
          "COMPONENT_PISTOL_VOLCANIC_GRIP_COLLECTOR",
          "COMPONENT_PISTOL_VOLCANIC_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_PISTOL_VOLCANIC_SIGHT_NARROW",
          "COMPONENT_PISTOL_VOLCANIC_SIGHT_WIDE",
          "COMPONENT_PISTOL_VOLCANIC_SIGHT_COLLECTOR",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_VOLCANIC_COLLECTOR",
        },

    },


    ["WEAPON_PISTOL_M1899"] = {
        ["BARREL"] = {
          "COMPONENT_PISTOL_M1899_BARREL_SHORT",
          "COMPONENT_PISTOL_M1899_BARREL_LONG",
        },
        ["CLIP"] = {
          "COMPONENT_PISTOL_M1899_CLIP",
        },
        ["GRIP"] = {
          "COMPONENT_PISTOL_M1899_GRIP",
          "COMPONENT_PISTOL_M1899_GRIP_IRONWOOD",
          "COMPONENT_PISTOL_M1899_GRIP_PEARL",
          "COMPONENT_PISTOL_M1899_GRIP_EBONY",
        },
        ["SIGHT"] = {
          "COMPONENT_PISTOL_M1899_SIGHT_NARROW",
          "COMPONENT_PISTOL_M1899_SIGHT_WIDE",
        },
    },

    ["WEAPON_REVOLVER_LEMAT"] = {
        ["BARREL"] = {
          "COMPONENT_REVOLVER_LEMAT_BARREL_SHORT",
          "COMPONENT_REVOLVER_LEMAT_BARREL_LONG",
        },
        ["GRIP"] = {
          "COMPONENT_REVOLVER_LEMAT_GRIP",
          "COMPONENT_REVOLVER_LEMAT_GRIP_PEARL",
          "COMPONENT_REVOLVER_LEMAT_GRIP_EBONY",
          "COMPONENT_REVOLVER_LEMAT_GRIP_IRONWOOD",
        },
        ["SIGHT"] = {
          "COMPONENT_REVOLVER_LEMAT_SIGHT_NARROW",
          "COMPONENT_REVOLVER_LEMAT_SIGHT_WIDE",
        },
    },

    ["WEAPON_REVOLVER_NAVY"] = {
        ["BARREL"] = {
          "COMPONENT_REVOLVER_NAVY_BARREL_SHORT",
          "COMPONENT_REVOLVER_NAVY_BARREL_LONG",
          "COMPONENT_REVOLVER_NAVY_BARREL_CROSSOVER",
        },
        ["GRIP"] = {
          "COMPONENT_REVOLVER_NAVY_GRIP",
          "COMPONENT_REVOLVER_NAVY_GRIP_IRONWOOD",
          "COMPONENT_REVOLVER_NAVY_GRIP_PEARL",
          "COMPONENT_REVOLVER_NAVY_GRIP_EBONY",
          "COMPONENT_REVOLVER_NAVY_GRIP_CROSSOVER",
        },
        ["SIGHT"] = {
          "COMPONENT_REVOLVER_NAVY_SIGHT_NARROW",
          "COMPONENT_REVOLVER_NAVY_SIGHT_WIDE",
          "COMPONENT_REVOLVER_NAVY_SIGHT_CROSSOVER",
        },
    },



    ["WEAPON_REPEATER_CARBINE"] = {

        ["GRIP"] = {
          "COMPONENT_REPEATER_CARBINE_GRIP",
          "COMPONENT_REPEATER_CARBINE_GRIP_IRONWOOD",
          "COMPONENT_REPEATER_CARBINE_GRIP_ENGRAVED",
          "COMPONENT_REPEATER_CARBINE_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_REPEATER_CARBINE_SIGHT_NARROW",
          "COMPONENT_REPEATER_CARBINE_SIGHT_WIDE",
        },
        ["CLIP"] = {
          "COMPONENT_REPEATER_CARBINE_CLIP",
        },
        ["TUBE"] = {
          "COMPONENT_REPEATER_CARBINE_TUBE",
        },
        ["WRAP"] = {
          "COMPONENT_REPEATER_CARBINE_WRAP1",
          "COMPONENT_REPEATER_CARBINE_WRAP2",
          "COMPONENT_REPEATER_CARBINE_WRAP3",
          "COMPONENT_REPEATER_CARBINE_WRAP4",
          "COMPONENT_REPEATER_CARBINE_WRAP5",
          "COMPONENT_REPEATER_CARBINE_WRAP6",
        },
    },


    ["WEAPON_REPEATER_HENRY"] = {

        ["GRIP"] = {
          "COMPONENT_REPEATER_HENRY_GRIP",
          "COMPONENT_REPEATER_HENRY_GRIP_IRONWOOD",
          "COMPONENT_REPEATER_HENRY_GRIP_ENGRAVED",
          "COMPONENT_REPEATER_HENRY_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_REPEATER_HENRY_SIGHT_NARROW",
          "COMPONENT_REPEATER_HENRY_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_REPEATER_HENRY_WRAP1",
          "COMPONENT_REPEATER_HENRY_WRAP2",
          "COMPONENT_REPEATER_HENRY_WRAP3",
          "COMPONENT_REPEATER_HENRY_WRAP4",
          "COMPONENT_REPEATER_HENRY_WRAP5",
          "COMPONENT_REPEATER_HENRY_WRAP6",
        },
    },


    ["WEAPON_REPEATER_EVANS"] = {

        ["GRIP"] = {
          "COMPONENT_REPEATER_EVANS_GRIP",
          "COMPONENT_REPEATER_EVANS_GRIP_IRONWOOD",
          "COMPONENT_REPEATER_EVANS_GRIP_ENGRAVED",
          "COMPONENT_REPEATER_EVANS_GRIP_BURLED",
          "COMPONENT_REPEATER_EVANS_GRIP_WINTER",
        },
        ["SIGHT"] = {
          "COMPONENT_REPEATER_EVANS_SIGHT_NARROW",
          "COMPONENT_REPEATER_EVANS_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_REPEATER_EVANS_WRAP",
          "COMPONENT_REPEATER_EVANS_WRAP2",
          "COMPONENT_REPEATER_EVANS_WRAP3",
          "COMPONENT_REPEATER_EVANS_WRAP4",
          "COMPONENT_REPEATER_EVANS_WRAP5",
          "COMPONENT_REPEATER_EVANS_WRAP6",
          "COMPONENT_REPEATER_EVANS_WRAP_WINTER",
        },
        ["FRAME_ENGRAVING"] = {
        	"COMPONENT_LONGARM_ROLE_ENGRAVING_EVANS_WINTER",
        },
    },



    ["WEAPON_REPEATER_WINCHESTER"] = {

        ["GRIP"] = {
          "COMPONENT_REPEATER_WINCHESTER_GRIP",
          "COMPONENT_REPEATER_WINCHESTER_GRIP_IRONWOOD",
          "COMPONENT_REPEATER_WINCHESTER_GRIP_ENGRAVED",
          "COMPONENT_REPEATER_WINCHESTER_GRIP_COLLECTOR",
          "COMPONENT_REPEATER_WINCHESTER_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_REPEATER_WINCHESTER_SIGHT_NARROW",
          "COMPONENT_REPEATER_WINCHESTER_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_REPEATER_WINCHESTER_WRAP1",
          "COMPONENT_REPEATER_WINCHESTER_WRAP2",
          "COMPONENT_REPEATER_WINCHESTER_WRAP3",
          "COMPONENT_REPEATER_WINCHESTER_WRAP4",
          "COMPONENT_REPEATER_WINCHESTER_WRAP5",
          "COMPONENT_REPEATER_WINCHESTER_WRAP6",
          "COMPONENT_REPEATER_WINCHESTER_WRAP_COLLECTOR",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_LONGARM_FRAME_ENGRAVING_WINCHESTER_COLLECTOR",
        },
    },




    ["WEAPON_RIFLE_VARMINT"] = {

        ["GRIP"] = {
          "COMPONENT_RIFLE_VARMINT_GRIP",
          "COMPONENT_RIFLE_VARMINT_GRIP_ENGRAVED",
          "COMPONENT_RIFLE_VARMINT_GRIP_IRONWOOD",
          "COMPONENT_RIFLE_VARMINT_GRIP_NATURALIST",
          "COMPONENT_RIFLE_VARMINT_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_REPEATER_PUMPACTION_SIGHT_NARROW",
          "COMPONENT_REPEATER_PUMPACTION_SIGHT_WIDE",
          "COMPONENT_RIFLE_VARMINT_SIGHT_NATURALIST",
        },
        ["CLIP"] = {
          "COMPONENT_RIFLE_VARMINT_CLIP",
          "COMPONENT_RIFLE_VARMINT_CLIP_ENGRAVED",
          "COMPONENT_RIFLE_VARMINT_CLIP_IRONWOOD",
          "COMPONENT_RIFLE_VARMINT_CLIP_NATURALIST",
          "COMPONENT_RIFLE_VARMINT_CLIP_BURLED",
        },
        ["WRAP"] = {
          "COMPONENT_RIFLE_VARMINT_WRAP1",
          "COMPONENT_RIFLE_VARMINT_WRAP2",
          "COMPONENT_RIFLE_VARMINT_WRAP3",
          "COMPONENT_RIFLE_VARMINT_WRAP4",
          "COMPONENT_RIFLE_VARMINT_WRAP5",
          "COMPONENT_RIFLE_VARMINT_WRAP6",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_LONGARM_ROLE_ENGRAVING_VARMINT_NATURALIST",
        },
    },





    ["WEAPON_RIFLE_BOLTACTION"] = {
        ["GRIP"] = {
          "COMPONENT_RIFLE_BOLTACTION_GRIP",
          "COMPONENT_RIFLE_BOLTACTION_GRIP_IRONWOOD",
          "COMPONENT_RIFLE_BOLTACTION_GRIP_ENGRAVED",
          "COMPONENT_RIFLE_BOLTACTION_GRIP_BOUNTY",
          "COMPONENT_RIFLE_BOLTACTION_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_RIFLE_BOLTACTION_SIGHT_WIDE",
          "COMPONENT_RIFLE_BOLTACTION_SIGHT_NARROW",
        },
        ["WRAP"] = {
          "COMPONENT_RIFLE_BOLTACTION_WRAP",
          "COMPONENT_RIFLE_BOLTACTION_WRAP2",
          "COMPONENT_RIFLE_BOLTACTION_WRAP3",
          "COMPONENT_RIFLE_BOLTACTION_WRAP4",
          "COMPONENT_RIFLE_BOLTACTION_WRAP5",
          "COMPONENT_RIFLE_BOLTACTION_WRAP6",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_LONGARM_FRAME_ENGRAVING_BOLTACTION_BOUNTY",
        },
    },

    ["WEAPON_RIFLE_ELEPHANT"] = {
    	["BARREL"] = {
    	  "COMPONENT_RIFLE_ELEPHANT_BARREL_SHORT",
    	  "COMPONENT_RIFLE_ELEPHANT_BARREL_LONG",
    	},
        ["GRIP"] = {
          "COMPONENT_RIFLE_ELEPHANT_GRIP",
          "COMPONENT_RIFLE_ELEPHANT_GRIP_IRONWOOD",
          "COMPONENT_RIFLE_ELEPHANT_GRIP_ENGRAVED",
          "COMPONENT_RIFLE_ELEPHANT_GRIP_BURLED",
        },
        ["MAG"] = {
          "COMPONENT_RIFLE_ELEPHANT_MAG",
          "COMPONENT_RIFLE_ELEPHANT_MAG_IRONWOOD",
          "COMPONENT_RIFLE_ELEPHANT_MAG_ENGRAVED",
          "COMPONENT_RIFLE_ELEPHANT_MAG_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_RIFLE_ELEPHANT_SIGHT_NARROW",
          "COMPONENT_RIFLE_ELEPHANT_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_RIFLE_ELEPHANT_WRAP1",
          "COMPONENT_RIFLE_ELEPHANT_WRAP2",
        },
    },

    ["WEAPON_RIFLE_SPRINGFIELD"] = {
        ["GRIP"] = {
          "COMPONENT_RIFLE_SPRINGFIELD_GRIP",
          "COMPONENT_RIFLE_SPRINGFIELD_GRIP_IRONWOOD",
          "COMPONENT_RIFLE_SPRINGFIELD_GRIP_ENGRAVED",
          "COMPONENT_RIFLE_SPRINGFIELD_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_RIFLE_SPRINGFIELD_SIGHT_NARROW",
          "COMPONENT_RIFLE_SPRINGFIELD_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_RIFLE_SPRINGFIELD_WRAP1",
          "COMPONENT_RIFLE_SPRINGFIELD_WRAP2",
          "COMPONENT_RIFLE_SPRINGFIELD_WRAP3",
          "COMPONENT_RIFLE_SPRINGFIELD_WRAP4",
          "COMPONENT_RIFLE_SPRINGFIELD_WRAP5",
          "COMPONENT_RIFLE_SPRINGFIELD_WRAP6",
        },
    },  



    ["WEAPON_SNIPERRIFLE_CARCANO"] = {
        ["GRIP"] = {
          "COMPONENT_RIFLE_CARCANO_GRIP",
          "COMPONENT_RIFLE_CARCANO_GRIP_ENGRAVED",
          "COMPONENT_RIFLE_CARCANO_GRIP_IRONWOOD",
          "COMPONENT_RIFLE_CARCANO_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_RIFLE_CARCANO_SIGHT_NARROW",
          "COMPONENT_RIFLE_CARCANO_SIGHT_WIDE",
        },
        ["CLIP"] = {
          "COMPONENT_RIFLE_CARCANO_CLIP",
          "COMPONENT_RIFLE_CARCANO_CLIP_EMPTY",
        },
        ["WRAP"] = {
          "COMPONENT_RIFLE_CARCANO_WRAP1",
          "COMPONENT_RIFLE_CARCANO_WRAP2",
          "COMPONENT_RIFLE_CARCANO_WRAP3",
          "COMPONENT_RIFLE_CARCANO_WRAP4",
          "COMPONENT_RIFLE_CARCANO_WRAP5",
          "COMPONENT_RIFLE_CARCANO_WRAP6",
        },
    },  




    ["WEAPON_SNIPERRIFLE_ROLLINGBLOCK"] = {
        ["GRIP"] = {
          "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP",
          "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_EXOTIC",
          "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_IRONWOOD",
          "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_ENGRAVED",
          "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_REAPER",
          "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_RIFLE_ROLLINGBLOCK_SIGHT_NARROW",
          "COMPONENT_RIFLE_ROLLINGBLOCK_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP1",
          "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP2",
          "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP3",
          "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP4",
          "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP5",
          "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP6",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_LONGARM_ROLE_ENGRAVING_ROLLINGBLOCK_REAPER",
        },
    },



    ["WEAPON_SHOTGUN_REPEATING"] = {
        ["BARREL"] = {
          "COMPONENT_SHOTGUN_REPEATING_BARREL_SHORT",
          "COMPONENT_SHOTGUN_REPEATING_BARREL_LONG",
        }, 
        ["GRIP"] = {
          "COMPONENT_SHOTGUN_REPEATING01_GRIP",
          "COMPONENT_SHOTGUN_REPEATING01_GRIP_IRONWOOD",
          "COMPONENT_SHOTGUN_REPEATING01_GRIP_ENGRAVED",
          "COMPONENT_SHOTGUN_REPEATING_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_SHOTGUN_REPEATING_SIGHT_NARROW",
          "COMPONENT_SHOTGUN_REPEATING_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_SHOTGUN_REPEATING01_WRAP1",
          "COMPONENT_SHOTGUN_REPEATING01_WRAP2",
          "COMPONENT_SHOTGUN_REPEATING_WRAP3",
          "COMPONENT_SHOTGUN_REPEATING_WRAP4",
          "COMPONENT_SHOTGUN_REPEATING_WRAP5",
          "COMPONENT_SHOTGUN_REPEATING_WRAP6",
        },
    },  


    ["WEAPON_SHOTGUN_PUMP"] = {
        ["BARREL"] = {
          "COMPONENT_SHOTGUN_PUMP_BARREL_SHORT",
          "COMPONENT_SHOTGUN_PUMP_BARREL_LONG",
          "COMPONENT_SHOTGUN_PUMP_BARREL_HALLOWEEN",
        }, 
        ["GRIP"] = {
          "COMPONENT_SHOTGUN_PUMP_GRIP",
          "COMPONENT_SHOTGUN_PUMP_GRIP_IRONWOOD",
          "COMPONENT_SHOTGUN_PUMP_GRIP_ENGRAVED",
          "COMPONENT_SHOTGUN_PUMP_GRIP_TRADER",
          "COMPONENT_SHOTGUN_PUMP_GRIP_BURLED",
          "COMPONENT_SHOTGUN_PUMP_GRIP_HALLOWEEN",
        },
        ["SIGHT"] = {
          "COMPONENT_SHOTGUN_PUMP_SIGHT_NARROW",
          "COMPONENT_SHOTGUN_PUMP_SIGHT_WIDE",
        },
        ["CLIP"] = {
          "COMPONENT_SHOTGUN_PUMP_CLIP",
          "COMPONENT_SHOTGUN_PUMP_CLIP_IRONWOOD",
          "COMPONENT_SHOTGUN_PUMP_CLIP_ENGRAVED",
          "COMPONENT_SHOTGUN_PUMP_CLIP_TRADER",
          "COMPONENT_SHOTGUN_PUMP_CLIP_BURLED",
          "COMPONENT_SHOTGUN_PUMP_CLIP_HALLOWEEN",
        },
        ["WRAP"] = {
          "COMPONENT_SHOTGUN_PUMP_WRAP1",
          "COMPONENT_SHOTGUN_PUMP_WRAP2",
          "COMPONENT_SHOTGUN_PUMP_WRAP3",
          "COMPONENT_SHOTGUN_PUMP_WRAP4",
          "COMPONENT_SHOTGUN_PUMP_WRAP5",
          "COMPONENT_SHOTGUN_PUMP_WRAP6",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_SHOTGUN_FRAME_ENGRAVING_PUMP_TRADER",
          "COMPONENT_LONGARM_ROLE_ENGRAVING_PUMP_HALLOWEEN",
        },
    },      


    ["WEAPON_SHOTGUN_DOUBLEBARREL"] = {
        ["BARREL"] = {
          "COMPONENT_SHOTGUN_DOUBLEBARREL_BARREL_SHORT",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_BARREL_LONG",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_BARREL_KRAMPUS",
        }, 
        ["GRIP"] = {
          "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_EXOTIC",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_IRONWOOD",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_ENGRAVED",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_KRAMPUS",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_SHOTGUN_DOUBLEBARREL_SIGHT_NARROW",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP1",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP2",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP3",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP4",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP5",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP6",
        },
        ["MAG"] = {
          "COMPONENT_SHOTGUN_DOUBLEBARREL_MAG",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_MAG_IRONWOOD",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_MAG_ENGRAVED",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_MAG_EXOTIC",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_MAG_KRAMPUS",
          "COMPONENT_SHOTGUN_DOUBLEBARREL_MAG_BURLED",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_LONGARM_ROLE_ENGRAVING_DOUBLEBARREL_KRAMPUS",
        },
    },



    ["WEAPON_SHOTGUN_SAWEDOFF"] = {
        ["GRIP"] = {
          "COMPONENT_SHOTGUN_SAWEDOFF_GRIP",
          "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_IRONWOOD",
          "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_EBONY",
          "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_MOONSHINER",
          "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_BURLED",
        },
        ["SIGHT"] = {
          "COMPONENT_SHOTGUN_SAWED_SIGHT_NARROW",
          "COMPONENT_SHOTGUN_SAWED_SIGHT_WIDE",
          "COMPONENT_SHOTGUN_SAWED_SIGHT_MOONSHINER",
        }, 
        ["WRAP"] = {
          "COMPONENT_SHOTGUN_SAWEDOFF_WRAP1",
          "COMPONENT_SHOTGUN_SAWEDOFF_WRAP2",
          "COMPONENT_SHOTGUN_SAWEDOFF_WRAP3",
          "COMPONENT_SHOTGUN_SAWEDOFF_WRAP4",
          "COMPONENT_SHOTGUN_SAWEDOFF_WRAP5",
        },
        ["STOCK"] = {
          "COMPONENT_SHOTGUN_SAWEDOFF_STOCK",
          "COMPONENT_SHOTGUN_SAWEDOFF_STOCK_IRONWOOD",
          "COMPONENT_SHOTGUN_SAWEDOFF_STOCK_EBONY",
          "COMPONENT_SHOTGUN_SAWEDOFF_STOCK_MOONSHINER",
          "COMPONENT_SHOTGUN_SAWEDOFF_STOCK_BURLED",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_LONGARM_ROLE_ENGRAVING_SAWEDOFF_MOONSHINER",
        },
    },  

    ["WEAPON_SHOTGUN_SEMIAUTO"] = {
        ["BARREL"] = {
          "COMPONENT_SHOTGUN_SEMIAUTO_BARREL_SHORT",
          "COMPONENT_SHOTGUN_SEMIAUTO_BARREL_LONG",
        },
        ["GRIP"] = {
          "COMPONENT_SHOTGUN_SEMIAUTO_GRIP",
          "COMPONENT_SHOTGUN_SEMIAUTO_GRIP_IRONWOOD",
          "COMPONENT_SHOTGUN_SEMIAUTO_GRIP_ENGRAVED",
          "COMPONENT_SHOTGUN_SEMIAUTO_GRIP_BURLED",
        }, 
        ["SIGHT"] = {
          "COMPONENT_SHOTGUN_SEMIAUTO_SIGHT_NARROW",
          "COMPONENT_SHOTGUN_SEMIAUTO_SIGHT_WIDE",
        },
        ["WRAP"] = {
          "COMPONENT_SHOTGUN_SEMIAUTO_WRAP1",
          "COMPONENT_SHOTGUN_SEMIAUTO_WRAP2",
          "COMPONENT_SHOTGUN_SEMIAUTO_WRAP3",
          "COMPONENT_SHOTGUN_SEMIAUTO_WRAP4",
          "COMPONENT_SHOTGUN_SEMIAUTO_WRAP5",
          "COMPONENT_SHOTGUN_SEMIAUTO_WRAP6",
        },
    },


    ["WEAPON_BOW_IMPROVED"] = {
        ["GRIP"] = {
          "COMPONENT_BOW_IMPROVED_GRIP",
          "COMPONENT_BOW_IMPROVED_GRIP_ALLIGATOR",
          "COMPONENT_BOW_IMPROVED_GRIP_HORNED",
          "COMPONENT_BOW_IMPROVED_GRIP_JAGUAR",
          "COMPONENT_BOW_IMPROVED_GRIP_WOODEN_INLAY",
        },
        ["CYLINDER_TINT"] = {   -- FRAME WOOD COLOR
          "COMPONENT_BOW_FRAME_TINT_A_1",
          "COMPONENT_BOW_FRAME_TINT_A_2",
          "COMPONENT_BOW_FRAME_TINT_A_3",
          "COMPONENT_BOW_FRAME_TINT_A_4",
          "COMPONENT_BOW_FRAME_TINT_A_5",
          "COMPONENT_BOW_FRAME_TINT_A_6",
          "COMPONENT_BOW_FRAME_TINT_A_7",
          "COMPONENT_BOW_FRAME_TINT_A_8",
        },
        ["BARREL_TINT"] = {   -- GRIP LEATHER COLOR
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_1",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_2",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_3",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_4",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_5",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_6",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_7",
          "COMPONENT_BOW_GRIPSTOCK_TINT_A_8",
        },
        ["TRIGGER_TINT"] = {  -- STRING COLOR
          "COMPONENT_BOW_TRIGGER_TINT_A_1",
          "COMPONENT_BOW_TRIGGER_TINT_A_2",
          "COMPONENT_BOW_TRIGGER_TINT_A_3",
          "COMPONENT_BOW_TRIGGER_TINT_A_4",
          "COMPONENT_BOW_TRIGGER_TINT_A_5",
          "COMPONENT_BOW_TRIGGER_TINT_A_6",
          "COMPONENT_BOW_TRIGGER_TINT_A_7",
          "COMPONENT_BOW_TRIGGER_TINT_A_8",
        },
        ["FRAME_VERTDATA"] = {
          "COMPONENT_BOW_ROLE_ENGRAVING_IMPROVED_ALLIGATOR",
          "COMPONENT_BOW_ROLE_ENGRAVING_IMPROVED_HORNED",
          "COMPONENT_BOW_ROLE_ENGRAVING_IMPROVED_JAGUAR",
          "COMPONENT_BOW_ROLE_ENGRAVING_IMPROVED_WOODEN_INLAY",
        },
    },


    ["WEAPON_MELEE_KNIFE"] = {
        ["GRIP"] = {
          "COMPONENT_MELEE_KNIFE02_GRIP",
          "COMPONENT_MELEE_KNIFE13_GRIP",
        }, 

    },

    ["WEAPON_THROWN_DYNAMITE"] = {
        ["TORCH_MATCHSTICK"] = {
          "COMPONENT_DYNAMITE_MOLOTOV_TORCH_MATCHSTICK",
        }, 
    },

    ["WEAPON_KIT_BINOCULARS"] = {
        ["TORCH_MATCHSTICK"] = {
          "COMPONENT_BINOCULARS_SCOPE01",
        }, 
    },

    ["WEAPON_FISHINGROD"] = {
        ["COMPONENT_FISHING_LINE"] = {
          "COMPONENT_FISHING_LINE",
        }, 
    },
}





































local shared_components = {
    ["SHORTARM"] = {

        ["TRIGGER_MATERIAL"] = {
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_1",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_2",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_3",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_4",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_5",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_6",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_7",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_8",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_9",
          "COMPONENT_SHORTARM_TRIGGER_MATERIAL_10",
        },  
        
        ["SIGHT_MATERIAL"] = {
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_1",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_2",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_3",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_4",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_5",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_6",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_7",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_8",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_9",
          "COMPONENT_SHORTARM_SIGHT_MATERIAL_10",
        },         
        
        ["HAMMER_MATERIAL"] = {
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_1",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_2",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_3",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_4",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_5",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_6",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_7",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_8",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_9",
          "COMPONENT_SHORTARM_HAMMER_MATERIAL_10",
        },  
        
        ["FRAME_MATERIAL"] = {
          "COMPONENT_SHORTARM_FRAME_MATERIAL_1",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_2",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_3",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_4",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_5",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_6",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_7",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_8",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_9",
          "COMPONENT_SHORTARM_FRAME_MATERIAL_10",
        },  

        ["FRAME_ENGRAVING"] = {
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_1",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_2",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_3",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_4",
        }, 

        ["FRAME_ENGRAVING_MATERIAL"] = {
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_1",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_2",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_3",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_4",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_5",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_6",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_7",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_8",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_9",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_10",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_11",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_12",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_13",
          "COMPONENT_SHORTARM_FRAME_ENGRAVING_MATERIAL_14",
        },

        ["BARREL_MATERIAL"] = {
          "COMPONENT_SHORTARM_BARREL_MATERIAL_1",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_2",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_3",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_4",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_5",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_6",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_7",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_8",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_9",
          "COMPONENT_SHORTARM_BARREL_MATERIAL_10",
        }, 

        ["BARREL_ENGRAVING"] = {
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_1",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_2",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_3",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_4",
        },

        ["BARREL_ENGRAVING_MATERIAL"] = {
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_1",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_2",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_3",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_4",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_5",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_6",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_7",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_8",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_9",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_10",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_11",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_12",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_13",
          "COMPONENT_SHORTARM_BARREL_ENGRAVING_MATERIAL_14",
        },

        ["CYLINDER_MATERIAL"] = {
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_1",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_2",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_3",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_4",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_5",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_6",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_7",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_8",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_9",
          "COMPONENT_SHORTARM_CYLINDER_MATERIAL_10",
        },  

        ["CYLINDER_ENGRAVING"] = {
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_1",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_2",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_3",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_4",
        }, 

        ["CYLINDER_ENGRAVING_MATERIAL"] = {
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_7",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_8",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_5",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_6",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_3",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_4",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_1",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_2",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_9",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_10",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_11",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_12",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_13",
          "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_MATERIAL_14",
        },        

        ["GRIP_MATERIAL"] = {
          "COMPONENT_SHORTARM_GRIP_MATERIAL_PEARL",
          "COMPONENT_SHORTARM_GRIP_MATERIAL_BURLED",
        },

        ["GRIPSTOCK_ENGRAVING"] = {
          "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_1",
          "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_2",
          "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_3",
          "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_4",
          "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_5",
          "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_6",
        }, 

        ["GRIPSTOCK_TINT"] = {
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_1",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_2",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_3",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_4",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_5",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_6",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_7",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_8",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_1",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_2",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_3",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_4",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_5",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_6",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_7",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_8",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_GUTTAPERCHA",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_PEARL",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_GRAY_BIRCH",
          "COMPONENT_SHORTARM_GRIPSTOCK_TINT_BURLED",
        },  

        ["BARREL_RIFLING"] = {
          "COMPONENT_SHORTARM_BARREL_RIFLING_1",
        },  


    },



    ["LONGARM"] = {

         ["TRIGGER_MATERIAL"] = {
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_1",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_2",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_3",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_4",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_5",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_6",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_7",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_8",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_9",
          "COMPONENT_LONGARM_TRIGGER_MATERIAL_10",
        }, 
        ["SIGHT_MATERIAL"] = {
          "COMPONENT_LONGARM_SIGHT_MATERIAL_1",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_2",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_3",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_4",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_5",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_6",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_7",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_8",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_9",
          "COMPONENT_LONGARM_SIGHT_MATERIAL_10",
        },
         ["HAMMER_MATERIAL"] = {
          "COMPONENT_LONGARM_HAMMER_MATERIAL_4",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_8",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_5",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_6",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_7",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_1",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_2",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_3",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_9",
          "COMPONENT_LONGARM_HAMMER_MATERIAL_10",
        },

        ["BARREL_MATERIAL"] = {
          "COMPONENT_LONGARM_BARREL_MATERIAL_1",
          "COMPONENT_LONGARM_BARREL_MATERIAL_2",
          "COMPONENT_LONGARM_BARREL_MATERIAL_3",
          "COMPONENT_LONGARM_BARREL_MATERIAL_4",
          "COMPONENT_LONGARM_BARREL_MATERIAL_5",
          "COMPONENT_LONGARM_BARREL_MATERIAL_6",
          "COMPONENT_LONGARM_BARREL_MATERIAL_7",
          "COMPONENT_LONGARM_BARREL_MATERIAL_8",
          "COMPONENT_LONGARM_BARREL_MATERIAL_9",
          "COMPONENT_LONGARM_BARREL_MATERIAL_10",
        },
        ["BARREL_ENGRAVING"] = {
          "COMPONENT_LONGARM_BARREL_ENGRAVING_1",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_3",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_2",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_4",
        }, 
        ["BARREL_ENGRAVING_MATERIAL"] = {
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_1",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_2",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_3",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_4",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_5",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_6",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_7",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_8",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_9",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_10",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_11",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_12",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_13",
          "COMPONENT_LONGARM_BARREL_ENGRAVING_MATERIAL_14",
        },

        ["CYLINDER_MATERIAL"] = {
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_1",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_2",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_3",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_4",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_5",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_6",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_7",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_8",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_9",
          "COMPONENT_LONGARM_CYLINDER_MATERIAL_10",
        }, 

        ["CYLINDER_ENGRAVING"] = {
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_1",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_2",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_3",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_4",
        },  
        ["CYLINDER_ENGRAVING_MATERIAL"] = {
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_1",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_2",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_3",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_4",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_5",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_6",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_7",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_8",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_9",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_10",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_11",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_12",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_13",
          "COMPONENT_LONGARM_CYLINDER_ENGRAVING_MATERIAL_14",
        }, 

        ["FRAME_MATERIAL"] = {
          "COMPONENT_LONGARM_FRAME_MATERIAL_1",
          "COMPONENT_LONGARM_FRAME_MATERIAL_2",
          "COMPONENT_LONGARM_FRAME_MATERIAL_3",
          "COMPONENT_LONGARM_FRAME_MATERIAL_4",
          "COMPONENT_LONGARM_FRAME_MATERIAL_5",
          "COMPONENT_LONGARM_FRAME_MATERIAL_6",
          "COMPONENT_LONGARM_FRAME_MATERIAL_7",
          "COMPONENT_LONGARM_FRAME_MATERIAL_8",
          "COMPONENT_LONGARM_FRAME_MATERIAL_9",
          "COMPONENT_LONGARM_FRAME_MATERIAL_10",
        }, 

        ["FRAME_ENGRAVING"] = {
          "COMPONENT_LONGARM_FRAME_ENGRAVING_1",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_2",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_3",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_4",
        }, 

        ["FRAME_ENGRAVING_MATERIAL"] = {
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_1",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_2",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_3",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_4",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_5",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_6",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_7",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_8",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_9",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_10",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_11",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_12",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_13",
          "COMPONENT_LONGARM_FRAME_ENGRAVING_MATERIAL_14",
        }, 

        ["GRIP_MATERIAL"] = {
          "COMPONENT_LONGARM_GRIP_MATERIAL_BURLED",
        }, 

        ["GRIPSTOCK_TINT"] = {
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_1",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_2",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_3",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_4",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_5",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_6",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_7",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_8",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_1",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_2",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_3",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_4",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_5",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_6",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_7",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_8",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_GUTTAPERCHA",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_PEARL",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_GRAY_BIRCH",
          "COMPONENT_LONGARM_GRIPSTOCK_TINT_BURLED",
        }, 

         ["GRIPSTOCK_ENGRAVING"] = {
          "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_1",
          "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_2",
          "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_3",
          "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_4",
          "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_5",
          "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_6",
        }, 


        ["WRAP_MATERIAL"] = {
          "COMPONENT_LONGARM_WRAP_MATERIAL_LEATHER",
          "COMPONENT_LONGARM_WRAP_MATERIAL_CLOTH",
        },  

        ["WRAP_TINT"] = {
          "COMPONENT_LONGARM_WRAP_TINT_WHITE",
          "COMPONENT_LONGARM_WRAP_TINT_BLACK",
          "COMPONENT_LONGARM_WRAP_TINT_A_1",
          "COMPONENT_LONGARM_WRAP_TINT_A_2",
          "COMPONENT_LONGARM_WRAP_TINT_A_3",
          "COMPONENT_LONGARM_WRAP_TINT_A_4",
          "COMPONENT_LONGARM_WRAP_TINT_A_5",
          "COMPONENT_LONGARM_WRAP_TINT_A_6",
          "COMPONENT_LONGARM_WRAP_TINT_A_7",
          "COMPONENT_LONGARM_WRAP_TINT_A_8",
          "COMPONENT_LONGARM_WRAP_TINT_B_1",
          "COMPONENT_LONGARM_WRAP_TINT_B_2",
          "COMPONENT_LONGARM_WRAP_TINT_B_3",
          "COMPONENT_LONGARM_WRAP_TINT_B_4",
          "COMPONENT_LONGARM_WRAP_TINT_B_5",
          "COMPONENT_LONGARM_WRAP_TINT_B_6",
          "COMPONENT_LONGARM_WRAP_TINT_B_7",
          "COMPONENT_LONGARM_WRAP_TINT_B_8",
          "COMPONENT_LONGARM_WRAP_TINT_C_1",
          "COMPONENT_LONGARM_WRAP_TINT_C_2",
          "COMPONENT_LONGARM_WRAP_TINT_C_3",
          "COMPONENT_LONGARM_WRAP_TINT_C_4",
          "COMPONENT_LONGARM_WRAP_TINT_C_5",
          "COMPONENT_LONGARM_WRAP_TINT_C_6",
          "COMPONENT_LONGARM_WRAP_TINT_C_7",
          "COMPONENT_LONGARM_WRAP_TINT_C_8",
          "COMPONENT_LONGARM_WRAP_TINT_C_9",
          "COMPONENT_LONGARM_WRAP_TINT_D_1",
          "COMPONENT_LONGARM_WRAP_TINT_D_2",
          "COMPONENT_LONGARM_WRAP_TINT_D_3",
          "COMPONENT_LONGARM_WRAP_TINT_D_4",
          "COMPONENT_LONGARM_WRAP_TINT_D_5",
          "COMPONENT_LONGARM_WRAP_TINT_D_6",
          "COMPONENT_LONGARM_WRAP_TINT_D_7",
          "COMPONENT_LONGARM_WRAP_TINT_D_8",
          "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_DEFAULT",
          "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_1",
          "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_2",
          "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_3",
          "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_4",
          "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_5",
          "COMPONENT_LONGARM_WRAP_TINT_NATIVE_DEFAULT",
          "COMPONENT_LONGARM_WRAP_TINT_NATIVE_1",
          "COMPONENT_LONGARM_WRAP_TINT_NATIVE_2",
          "COMPONENT_LONGARM_WRAP_TINT_NATIVE_3",
          "COMPONENT_LONGARM_WRAP_TINT_NATIVE_4",
          "COMPONENT_LONGARM_WRAP_TINT_NATIVE_5",
          "COMPONENT_LONGARM_WRAP_TINT_TARTAN_DEFAULT",
          "COMPONENT_LONGARM_WRAP_TINT_TARTAN_1",
          "COMPONENT_LONGARM_WRAP_TINT_TARTAN_2",
          "COMPONENT_LONGARM_WRAP_TINT_TARTAN_3",
          "COMPONENT_LONGARM_WRAP_TINT_TARTAN_4",
          "COMPONENT_LONGARM_WRAP_TINT_TARTAN_5",
          "COMPONENT_LONGARM_WRAP_TINT_E_1",
          "COMPONENT_LONGARM_WRAP_TINT_E_2",
          "COMPONENT_LONGARM_WRAP_TINT_E_3",
          "COMPONENT_LONGARM_WRAP_TINT_E_4",
          "COMPONENT_LONGARM_WRAP_TINT_E_5",
          "COMPONENT_LONGARM_WRAP_TINT_E_6",
          "COMPONENT_LONGARM_WRAP_TINT_E_7",
          "COMPONENT_LONGARM_WRAP_TINT_E_8",
          "COMPONENT_LONGARM_WRAP_TINT_E_9",
          "COMPONENT_LONGARM_WRAP_TINT_E_10",
        },
        ["STRAP"] = {
		  "COMPONENT_REPEATER_STRAP01",
      	  "COMPONENT_RIFLE_CS_STRAP01",
      	  "COMPONENT_REPEATER_CLOTH_STRAP01",
      	  "COMPONENT_LEFTSHOULDER_STRAP01",
        },          
        ["STRAP_TINT"] = {
          "COMPONENT_LONGARM_STRAP_TINT_A_1",
          "COMPONENT_LONGARM_STRAP_TINT_A_2",
          "COMPONENT_LONGARM_STRAP_TINT_A_3",
          "COMPONENT_LONGARM_STRAP_TINT_A_4",
          "COMPONENT_LONGARM_STRAP_TINT_A_5",
          "COMPONENT_LONGARM_STRAP_TINT_A_6",
          "COMPONENT_LONGARM_STRAP_TINT_A_7",
          "COMPONENT_LONGARM_STRAP_TINT_A_8",
        }, 

        ["BARREL_RIFLING"] = {
          "COMPONENT_LONGARM_BARREL_RIFLING_1",
        }, 

    	["SCOPE"] = {
          "COMPONENT_RIFLE_SCOPE02",
          "COMPONENT_RIFLE_SCOPE03",
          "COMPONENT_RIFLE_SCOPE04",
        },

    },


    ["SHOTGUN"] = {
        ["CYLINDER_ENGRAVING"] = {
          "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_1",
          "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_2",
          "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_3",
          "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_4",
        },
        ["FRAME_ENGRAVING"] = {
          "COMPONENT_SHOTGUN_FRAME_ENGRAVING_1",
          "COMPONENT_SHOTGUN_FRAME_ENGRAVING_2",
          "COMPONENT_SHOTGUN_FRAME_ENGRAVING_3",
          "COMPONENT_SHOTGUN_FRAME_ENGRAVING_4",
        },
        ["BARREL_ENGRAVING"] = {
          "COMPONENT_SHOTGUN_BARREL_ENGRAVING_1",
          "COMPONENT_SHOTGUN_BARREL_ENGRAVING_2",
          "COMPONENT_SHOTGUN_BARREL_ENGRAVING_3",
          "COMPONENT_SHOTGUN_BARREL_ENGRAVING_4",
        },
    },

    ["MELEE_BLADE"] = {
        ["MELEE_BLADE_MATERIAL"] = {
          "COMPONENT_MELEE_BLADE_MATERIAL_7",
          "COMPONENT_MELEE_BLADE_MATERIAL_5",
          "COMPONENT_MELEE_BLADE_MATERIAL_6",
          "COMPONENT_MELEE_BLADE_MATERIAL_3",
          "COMPONENT_MELEE_BLADE_MATERIAL_1",
          "COMPONENT_MELEE_BLADE_MATERIAL_2",
          "COMPONENT_MELEE_BLADE_MATERIAL_8",
          "COMPONENT_MELEE_BLADE_MATERIAL_4",
          "COMPONENT_MELEE_BLADE_MATERIAL_9",
        }, 
        ["MELEE_BLADE_ENGRAVING"] = {
          "COMPONENT_MELEE_BLADE_ENGRAVING_1",
          "COMPONENT_MELEE_BLADE_ENGRAVING_2",
          "COMPONENT_MELEE_BLADE_ENGRAVING_3",
        }, 
        ["MELEE_BLADE_ENGRAVING_MATERIAL"] = {
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_1",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_2",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_3",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_4",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_5",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_6",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_7",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_8",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_9",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_11",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_12",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_13",
          "COMPONENT_MELEE_BLADE_ENGRAVING_MATERIAL_14",
        },  

        ["GRIP_TINT"] = {
          "COMPONENT_MELEE_GRIP_TINT_A_1",
          "COMPONENT_MELEE_GRIP_TINT_A_2",
          "COMPONENT_MELEE_GRIP_TINT_A_3",
          "COMPONENT_MELEE_GRIP_TINT_A_4",
          "COMPONENT_MELEE_GRIP_TINT_A_5",
          "COMPONENT_MELEE_GRIP_TINT_A_6",
          "COMPONENT_MELEE_GRIP_TINT_A_7",
          "COMPONENT_MELEE_GRIP_TINT_A_8",
          "COMPONENT_MELEE_GRIP_TINT_B_1",
          "COMPONENT_MELEE_GRIP_TINT_B_2",
          "COMPONENT_MELEE_GRIP_TINT_B_3",
          "COMPONENT_MELEE_GRIP_TINT_B_4",
          "COMPONENT_MELEE_GRIP_TINT_B_5",
          "COMPONENT_MELEE_GRIP_TINT_B_6",
          "COMPONENT_MELEE_GRIP_TINT_B_7",
          "COMPONENT_MELEE_GRIP_TINT_B_8",
          "COMPONENT_MELEE_GRIP_TINT_GRAY_BIRCH",
        },

    },    
}


