--		EXAMPLE. MAKE FIRE BREATH FROM PED HEAD:
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
--		local new_ptfx_dictionary = "anm_fire_dancers"
--		local new_ptfx_name = "ent_anim_fire_breathe_loop"
--
--		local is_particle_effect_active = false
--		local current_ptfx_dictionary = new_ptfx_dictionary
--		local current_ptfx_name = new_ptfx_name
--
--		local current_ptfx_handle_id = false
--
--		local bone_index = 247   -- ["PH_Head"]  = {bone_index = 247, bone_id = 57278},
--
--		local ptfx_offcet_x = 0.0
--		local ptfx_offcet_y = 0.0
--		local ptfx_offcet_z = 0.0
--		local ptfx_rot_x = -90.0
--		local ptfx_rot_y = 0.0
--		local ptfx_rot_z = 0.0
--		local ptfx_scale = 1.0
--		local ptfx_axis_x = 0
--		local ptfx_axis_y = 0
--		local ptfx_axis_z = 0
--
--
--		Citizen.CreateThread(function()
--		   	while true do
--		        Citizen.Wait(0)
--		        if Citizen.InvokeNative(0x91AEF906BCA88877,0, 0x17BEC168) then   -- just pressed E
--		        	if not is_particle_effect_active then
--		        		current_ptfx_dictionary = new_ptfx_dictionary
--						current_ptfx_name = new_ptfx_name
--		        		if not Citizen.InvokeNative(0x65BB72F29138F5D6, GetHashKey(current_ptfx_dictionary)) then -- HasNamedPtfxAssetLoaded
--		        			Citizen.InvokeNative(0xF2B2353BBC0D4E8F, GetHashKey(current_ptfx_dictionary))  -- RequestNamedPtfxAsset
--		        			local counter = 0
--		        			while not Citizen.InvokeNative(0x65BB72F29138F5D6, GetHashKey(current_ptfx_dictionary)) and counter <= 300 do  -- while not HasNamedPtfxAssetLoaded
--		        				Citizen.Wait(0)
--		        			end
--		        		end
--		    			if Citizen.InvokeNative(0x65BB72F29138F5D6, GetHashKey(current_ptfx_dictionary)) then  -- HasNamedPtfxAssetLoaded
--		    				Citizen.InvokeNative(0xA10DB07FC234DD12, current_ptfx_dictionary) -- UseParticleFxAsset
--
--		    				current_ptfx_handle_id = Citizen.InvokeNative(0x9C56621462FFE7A6,current_ptfx_name,PlayerPedId(),ptfx_offcet_x,ptfx_offcet_y,ptfx_offcet_z,ptfx_rot_x,ptfx_rot_y,ptfx_rot_z,bone_index,ptfx_scale,ptfx_axis_x,ptfx_axis_y,ptfx_axis_z) -- StartNetworkedParticleFxLoopedOnEntityBone
--		    				--current_ptfx_handle_id =  Citizen.InvokeNative(0x8F90AB32E1944BDE,current_ptfx_name,PlayerPedId(),ptfx_offcet_x,ptfx_offcet_y,ptfx_offcet_z,ptfx_rot_x,ptfx_rot_y,ptfx_rot_z,ptfx_scale,ptfx_axis_x,ptfx_axis_y,ptfx_axis_z)    -- StartNetworkedParticleFxLoopedOnEntity
--		    				is_particle_effect_active = true
--						else
--							print("cant load ptfx dictionary!")
--		    			end
--		        	else
--		        		if current_ptfx_handle_id then
--							if Citizen.InvokeNative(0x9DD5AFF561E88F2A, current_ptfx_handle_id) then   -- DoesParticleFxLoopedExist
--								Citizen.InvokeNative(0x459598F579C98929, current_ptfx_handle_id, false)   -- RemoveParticleFx
--							end
--						end
--						current_ptfx_handle_id = false
--						is_particle_effect_active = false
--		        	end
--		        end
--		    end
--		end)
--
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

-- ptfx_assets_looped = {
-- 	[ptfx_dictionary] = {ptfx_name},
-- }

local ptfx_assets_looped = {
	["anm_climbing"] = {
		"ent_anim_climbing_debris",
		"ent_anim_debris_falling",
	},
	["scr_net_player_signal"] = {
		"scr_net_player_signal",
	},
	["des_alchemist"] = {
		"ent_amb_alchemist_post_cloud_smk",
	},
	["anm_crafting"] = {
		"ent_anim_bottle_pour_medicine",
		"ent_anim_cauldron_drugs",
		"ent_anim_craft_pestle_grind",
	},
	["anm_odr"] = {
		"ent_anim_odr_knife_meat",
	},
	["scr_mob2"] = {
		"scr_mob2_fog_cem",
	},
	["scr_beat_train_tracks"] = {
		"scr_beat_train_sparks",
	},
	["scr_native1"] = {
		"scr_native1_campfire_smoke",
	},
	["scr_campfires"] = {
		"ent_amb_campfire_smoke_distance",
		"ent_amb_campfire_smoke_distance_gang",
	},
	["cut_rdopn"] = {
		"cs_rdopn_faucet_pour",
	},
	["anm_water"] = {
		"ent_amb_water_drips_edge",
		"ent_anim_bottle_pour_water",
		"ent_anim_bottle_pour_whisky",
		"ent_anim_bubble_stream",
		"ent_anim_bubble_stream_ped",
		"ent_anim_mob5_face_drips",
		"ent_anim_moonshine_pour_shot",
		"ent_anim_ntv3_steam_leak",
		"ent_anim_oil_drips",
		"ent_anim_ped_finger_drips",
		"ent_anim_ped_ind3_water_drips",
		"ent_anim_ped_water_drips",
		"ent_anim_ped_water_wade_ripples",
		"ent_anim_sht_steam",
		"ent_anim_sht_steam_thick",
		"ent_anim_steam_horseboat_ripple",
		"ent_anim_steam_horseboat_splash",
		"ent_anim_water_bucket_drips",
		"ent_anim_water_bucket_fill",
		"ent_anim_water_gold_pan_loop",
		"ent_anim_water_kettle_splash_looped",
		"ent_anim_water_pan_submerge",
		"ent_anim_water_pump_pour",
		"ent_anim_water_shakeoff",
		"ent_anim_water_torture",
		"ent_anim_water_washing",
		"ent_anim_whiskey_pour_shot",
	},
	["scr_poisoned_well"] = {
		"scr_poisoned_well_fog_anim",
	},
	["anm_fin"] = {
		"ent_anim_fin_dislodged_gravel",
		"ent_anim_fin_tackle_dust",
		"ent_anim_fin_tackle_gravel",
		"ent_anim_train_roll_dust",
	},
	["scr_mg_bathing"] = {
		"scr_mg_bathing_foam_forearm",
		"scr_mg_bathing_foam_head",
		"scr_mg_bathing_foam_torso",
		"scr_mg_bathing_foam_upperarm",
		"scr_mg_bathing_tub_steam",
	},
	["scr_winter1"] = {
		"scr_winter1_barn_snow",
		"scr_winter1_cabin_fire",
		"scr_winter1_cabin_fire_roof",
		"scr_winter1_cabin_fire_roof_fall",
		"scr_winter1_cloud_density_anim",
		"scr_winter1_fog_cover",
	},
	["scr_guama1"] = {
		"scr_guama1_ship_leaking",
	},
	["scr_net_dust"] = {
		"scr_flow_camp_mp",
	},
	["scr_fme_spawn_effects"] = {
		"scr_animal_poop_flies",
	},
	["cut_utopia2"] = {
		"cs_utopia2_water_drips",
		"cs_utopia2_water_splash_loop",
	},
	["scr_hideout_shadybelle"] = {
		"scr_hideout_sb_fuse",
	},
	["anm_dishwash"] = {
		"ent_anim_dish_wash_arm_wade",
		"ent_anim_dish_wash_bowl_drips",
		"ent_anim_dish_wash_plate_drips",
		"ent_anim_dish_wash_splashes",
		"ent_anim_dish_wash_spoon_drips",
	},
	["scr_net_target_races"] = {
		"scr_net_target_fire_ring_mp",
	},
	["scr_net_pony_express"] = {
		"scr_net_race_smoke",
	},
	["scr_generic"] = {
		"ent_amb_insect_fly_swarm",
		"env_smoke",
		"scr_event_glint",
		"scr_gen_shiny_bling",
	},
	["scr_marston"] = {
		"ent_amb_milk_bubbles",
		"scr_mg_milking",
	},
	["scr_net_camp"] = {
		"eagle_eye_clue_animal_transform",
		"scr_net_animal_ghost",
		"scr_net_animal_ghost_boar",
		"scr_net_animal_ghost_head",
		"scr_net_animal_ghost_limb",
		"scr_net_animal_ghost_sma",
		"scr_net_spirit_animal_fade",
	},
	["scr_hideout_ironcloud"] = {
		"scr_ironcloud_fire_extinguish",
		"scr_ironcloud_fire_object",
	},
	["des_moon1"] = {
		"ent_anm_generic_fire_field",
		"ent_ray_moon1_roof_fire",
	},
	["des_mob3"] = {
		"ent_ray_mob3_smoke_post",
		"ent_ray_mob3_smoke_trail",
		"ent_ray_mob3_trolley_sparks",
		"scr_mob3_proj_dynamite_trail",
	},
	["scr_net_moon5"] = {
		"scr_net_moon2_still_fire",
		"scr_net_moon5_player_smoke",
	},
	["scr_discoverables"] = {
		"ent_amb_steam_geyser",
		"ent_amb_witch_cauldron_bubble",
		"ent_amb_witch_cauldron_steam",
		"scr_disc_meteor_shower",
		"scr_disc_whispering_trees",
	},
	["scr_sadie2"] = {
		"scr_sad2_liq_pour",
	},
	["scr_player_camp"] = {
		"ent_amb_campfire_dynamic",
	},
	["scr_agnesdowd_ghost"] = {
		"scr_ped_ghost_haze_stage1",
	},
	["scr_proc_homerobberies"] = {
		"scr_homerob_chez_barn_fire",
	},
	["anm_wnt"] = {
		"ent_anim_door_snow_drifts",
		"ent_anim_lantern_fire_win1",
		"ent_anim_train_sparks",
		"ent_anim_winter1_fireplace_start",
	},
	["anm_work"] = {
		"ent_anim_bale_debris_trail",
		"ent_anim_brush_drip_trail",
		"ent_anim_brush_dust",
		"ent_anim_bucket_fill_splash",
		"ent_anim_constant_sparks",
		"ent_anim_cotton_dump_loop",
		"ent_anim_cottonbale_leak",
		"ent_anim_feed_looping",
		"ent_anim_hay_pitchfork_lift",
		"ent_anim_hay_pitchfork_lift_fork_hay",
		"ent_anim_saw_wood",
		"ent_anim_scrape_ground_debris",
		"ent_anim_steam_horsegelding",
		"ent_anim_table_wipe",
		"ent_anim_water_cloth_squeeze",
		"ent_anim_work_rake",
	},
	["scr_beat_burning_bodies"] = {
		"scr_beat_burning_body_fire",
		"scr_beat_burning_body_smk",
		"scr_beat_burning_body_smk_start",
	},
	["scr_mudtown5"] = {
		"proj_dynamite_trail",
	},
	["scr_native3"] = {
		"scr_natv3_fire_oil_field",
		"scr_natv3_fire_oil_plume",
		"scr_natv3_generic_fire",
	},
	["scr_mob3"] = {
		"scr_mob3_proj_dynamite_trail",
	},
	["scr_crackpot"] = {
		"scr_crackpot_rc_sparks",
		"scr_crackpot_sink_bubbles",
		"scr_crackpot_tesla_coil",
		"scr_crackpot_torpedo_spray",
	},
	["anm_foodprep"] = {
		"ent_anim_bbq",
		"ent_anim_fly_swarm",
		"ent_anim_food_seasoning_shake",
		"ent_anim_food_seasoning_shake_into_hand",
		"ent_anim_food_seasoning_sprinkle",
		"ent_anim_foodprep_bits",
		"ent_anim_gut_blood_drain",
		"ent_anim_gut_blood_saw",
		"ent_anim_gut_dried_meat_saw",
		"ent_anim_ladle_drip_trail",
		"ent_anim_ladle_drips",
		"ent_anim_ladle_food_pour",
		"ent_anim_ladle_steam",
		"ent_anim_ladle_steam_int",
		"ent_anim_milk_pour",
		"ent_anim_pan_steam",
		"ent_anim_plate_steam",
	},
	["scr_std1"] = {
		"scr_nbd1_bankwall_fire_linger",
		"scr_nbd1_bankwall_smolder",
		"scr_nbd1_exp_bankwall_fall_dust",
		"scr_nbd1_exp_bankwall_linger",
		"scr_nbd1_smoke_01",
		"scr_nbd1_smoke_02",
		"scr_nbd1_smoke_chimney",
		"scr_nbd1_smoke_chimney_rect",
		"scr_nbd1_smoke_chimney_split",
		"scr_nbd1_smoke_pipe_main",
		"scr_nbd1_smoke_pipe_sub",
	},
	["des_utopia1"] = {
		"ent_ray_utopia1_debtrail",
	},
	["anm_coffee"] = {
		"ent_anim_coffee_drips",
		"ent_anim_coffee_steam",
		"ent_anim_coffee_steam_cold",
		"ent_anim_liquid_drips",
	},
	["scr_beat_gator_hunters"] = {
		"scr_beat_gator_blood_water",
		"scr_beat_gator_splash",
	},
	["scr_gang2"] = {
		"scr_gang2_air_balloon_smoke",
	},
	["cut_rrtl"] = {
		"cs_rrtl_electric_arcs",
		"cs_rrtl_lightning",
		"cs_rrtl_smoulder_smoke",
	},
	["scr_metal_detector"] = {
		"scr_mp_metal_detector_sparks",
	},
	["scr_net_gangbounty"] = {
		"scr_net_gangbounty_smoke",
	},
	["scr_bou1"] = {
		"scr_bou1_climb_dust_loop",
		"scr_bou1_ped_water_splash",
	},
	["scr_smuggler1"] = {
		"scr_smug_fog",
	},
	["anm_rmllr"] = {
		"ent_amb_insect_fly_swarm",
		"ent_anim_dusty_interior",
	},
	["scr_beat_bloated_corpse"] = {
		"scr_beat_corpse_water_bubble",
	},
	["scr_winter2"] = {
		"scr_blood_drips",
		"scr_winter2_smoke",
	},
	["scr_beat_campfire_ambush"] = {
		"scr_campfire_ambush_fire_extinguish",
	},
	["anm_animals"] = {
		"ent_anim_animal_foot_dust",
		"ent_anim_animal_water_drink",
		"ent_anim_animal_water_drink_drips",
		"ent_anim_bear_dig_dirt_looped",
		"ent_anim_beaver_eat_tree_splinters",
		"ent_anim_bird_water_drink",
		"ent_anim_bird_water_drink_drips",
		"ent_anim_boar_spray",
		"ent_anim_buffalo_fight_dust",
		"ent_anim_buffalo_roll_dust",
		"ent_anim_dog_peeing",
		"ent_anim_dog_poo",
		"ent_anim_dog_roll_dust",
		"ent_anim_dog_water_drink",
		"ent_anim_drink_drip_trail",
		"ent_anim_fish_breath_bubbles",
		"ent_anim_fish_flee_bubbles",
		"ent_anim_hen_flee",
		"ent_anim_horse_dust_spread",
		"ent_anim_horse_dust_spread_preload",
		"ent_anim_horse_graze_chew",
		"ent_anim_horse_peeing",
		"ent_anim_horse_water_drink",
		"ent_anim_ped_beaver_ripple",
		"ent_anim_slide_dust",
		"ent_anim_sparrow_bath_splash",
		"ent_anim_squirrel_pounce_dust",
	},
	["anm_oddf"] = {
		"ent_anim_firework_fuse",
		"ent_anim_oddf_campfire",
		"ent_anim_oddf_firework_trail",
	},
	["des_guama3_tower_exp"] = {
		"ent_ray_guama3_tower_trail",
	},
	["anm_peepingtom"] = {
		"ent_anim_opium_pipe_exhale",
		"ent_anim_opium_pipe_smoke",
	},
	["scr_mg_cleaning_stalls"] = {
		"scr_mg_stalls_manure_flies",
	},
	["cut_winter"] = {
		"cs_cig_smoke",
		"cs_ped_wade_snow",
	},
	["scr_cornwall1"] = {
		"scr_crn1_lantern_fire",
	},
	["anm_rally"] = {
		"ent_anim_rally_cross_fire_loop",
	},
	["scr_dusters1"] = {
		"scr_dusters1_camp_smoke",
	},
	["scr_dzoavitsclaim"] = {
		"scr_dzoav_coal_dump",
		"scr_dzoav_coal_dump_col",
		"scr_dzoav_fire_roof",
		"scr_dzoav_fire_window",
		"scr_dzoav_mine_haze",
		"scr_dzoav_waste_dump",
		"scr_dzoav_waste_dump_col",
	},
	["scr_net_adversary_team_border"] = {
		"scr_net_team_border",
	},
	["anm_sal"] = {
		"ent_anim_sal1_drown_splash_loop",
	},
	["scr_distance_smoke"] = {
		"scr_campfire_distance_light",
		"scr_campfire_distance_smoke_lod",
		"scr_campfire_distance_smoke_script",
		"scr_campfire_distance_smoke_sma",
	},
	["scr_crafting"] = {
		"scr_crafting_animal_potions",
	},
	["des_tree_fall"] = {
		"ent_ray_tree_fall_leaves",
	},
	["anm_homerobbery"] = {
		"ent_anim_aberdeen_bottle_pour",
		"ent_anim_chimney_disturb_soot",
		"ent_anim_grain_sift",
	},
	["anm_lom"] = {
		"ent_anim_lom_cig_smoke_cigar",
		"ent_anim_lom_pipe_smoke",
		"ent_anim_lom_throat_slit",
		"ent_anim_lom_train_pipe_smoke",
		"ent_anim_lom_train_piston_gland_steam",
		"ent_anim_lom_train_steam_ambient",
	},
	["scr_happyfam"] = {
		"scr_happyfam_door_smk",
		"scr_happyfam_pipe_smk",
		"scr_happyfam_room_smk",
	},
	["scr_loanshark_hunter2"] = {
		"scr_loanshark_hunter2_smoke",
	},
	["scr_beat_rally"] = {
		"scr_beat_rally_cross_fire_loop",
	},
	["scr_beat_voodoo_ritual"] = {
		"scr_beat_voodoo_blood_drips",
	},
	["scr_arch_jameson2"] = {
		"fire_gunpowder_half",
		"fire_gunpowder_one",
		"fire_gunpowder_pool",
		"fire_gunpowder_two",
	},
	["des_utopia2"] = {
		"ent_ray_utopia2_rock_dirt",
		"ent_ray_utopia2_tree_fall_needles",
		"ent_ray_utopia2_uw_silt",
	},
	["anm_script_re"] = {
		"ent_anim_moths_swarm_night",
		"ent_anim_snow_drifts",
	},
	["scr_reverend1"] = {
		"scr_rev_puke",
	},
	["anm_collision"] = {
		"ent_anim_roll_dust",
		"ent_anim_roll_gravel",
		"ent_anim_scrape_dust_joint",
		"ent_anim_scrape_dust_limb",
		"ent_anim_scrape_mud_joint",
		"ent_anim_scrape_mud_limb",
		"ent_anim_scrape_mud_soft_limb",
	},
	["core"] = {
		"blood_cd_blood_trail",
		"blood_cd_blood_trail_gore",
		"bullet_laser_sight",
		"bullet_shotgun_tracer",
		"bullet_tracer",
		"bullet_tracer_incendiary",
		"decal_water_blood",
		"ent_amb_ann_coal",
		"ent_amb_ann_coal_bits",
		"ent_amb_ann_coal_chute",
		"ent_amb_ann_coal_chute_dive",
		"ent_amb_ann_coal_mesh",
		"ent_amb_ann_falling_dust",
		"ent_amb_ann_smoke_street",
		"ent_amb_ann_smokegroup_01",
		"ent_amb_ann_smokegroup_02",
		"ent_amb_ann_smokegroup_03",
		"ent_amb_ann_sprinkler",
		"ent_amb_ann_vapor",
		"ent_amb_bathtub_lather",
		"ent_amb_blacksmith_fire",
		"ent_amb_boat_idle_smoke",
		"ent_amb_bonfire",
		"ent_amb_bonfire_mp",
		"ent_amb_bonfire_nosmoke",
		"ent_amb_bubble_stream",
		"ent_amb_campfire_lrg",
		"ent_amb_campfire_lrg_base",
		"ent_amb_campfire_lrg_int",
		"ent_amb_campfire_lrg_mp",
		"ent_amb_campfire_sma",
		"ent_amb_campfire_sma_base",
		"ent_amb_campfire_sma_nosmoke",
		"ent_amb_campfire_sma_under",
		"ent_amb_campfire_smoke_distance",
		"ent_amb_campfire_smoke_distance_dark",
		"ent_amb_campfire_smoke_distance_gang",
		"ent_amb_campfire_smoke_distance_trail",
		"ent_amb_campfire_smolder",
		"ent_amb_candle_flame",
		"ent_amb_candle_flame_distance",
		"ent_amb_candle_flame_lit",
		"ent_amb_candle_flame_smoke",
		"ent_amb_cave_poison",
		"ent_amb_cave_poison_splash",
		"ent_amb_cig_smoke",
		"ent_amb_cig_smoke_linger",
		"ent_amb_cig_smoke_linger_casino",
		"ent_amb_cig_smoke_linger_lite",
		"ent_amb_cliff_snowfall",
		"ent_amb_cook_bubble",
		"ent_amb_corpse_bleeding",
		"ent_amb_door_snow_drifts",
		"ent_amb_drain_splash",
		"ent_amb_dust_motes",
		"ent_amb_dust_motes_window",
		"ent_amb_elec_crackle",
		"ent_amb_exhaust_thick",
		"ent_amb_exhaust_thin",
		"ent_amb_falling_embers",
		"ent_amb_falling_leaves_birch_l",
		"ent_amb_falling_leaves_birch_s",
		"ent_amb_falling_leaves_ficus_l",
		"ent_amb_falling_leaves_ficus_s",
		"ent_amb_falling_leaves_flower",
		"ent_amb_falling_leaves_maple_l",
		"ent_amb_falling_leaves_maple_s",
		"ent_amb_falling_leaves_moss",
		"ent_amb_falling_leaves_oak_l",
		"ent_amb_falling_leaves_oak_s",
		"ent_amb_falling_leaves_palm",
		"ent_amb_falling_leaves_pine",
		"ent_amb_falling_tree_leaves",
		"ent_amb_fire_lit",
		"ent_amb_fire_moon_still",
		"ent_amb_fire_oil_field",
		"ent_amb_fog_ring",
		"ent_amb_fountain_double",
		"ent_amb_fountain_mesh",
		"ent_amb_fountain_mesh_bottom",
		"ent_amb_fountain_nb_double",
		"ent_amb_fountain_new_gar",
		"ent_amb_fountain_spout",
		"ent_amb_furnace_fire_lrg",
		"ent_amb_furnace_heat_haze",
		"ent_amb_generic_fire_area",
		"ent_amb_generic_fire_area_spread",
		"ent_amb_generic_fire_crawling",
		"ent_amb_generic_fire_doorway",
		"ent_amb_generic_fire_field",
		"ent_amb_generic_fire_field_full",
		"ent_amb_generic_fire_field_full_sma",
		"ent_amb_generic_fire_field_nosmoke",
		"ent_amb_generic_fire_field_smoke",
		"ent_amb_generic_fire_fog",
		"ent_amb_generic_fire_int_fog",
		"ent_amb_generic_fire_line",
		"ent_amb_generic_fire_mesh",
		"ent_amb_generic_fire_mesh_no_smoke",
		"ent_amb_generic_fire_mesh_v1",
		"ent_amb_generic_fire_plume",
		"ent_amb_generic_fire_rm_smoke",
		"ent_amb_generic_fire_roof",
		"ent_amb_generic_fire_roof_angle",
		"ent_amb_generic_fire_smoke_plume",
		"ent_amb_generic_fire_up",
		"ent_amb_generic_fire_win",
		"ent_amb_generic_fire_win_nosmoke",
		"ent_amb_generic_roof_smoke_fog",
		"ent_amb_generic_smolder_area",
		"ent_amb_generic_smolder_area_nopre",
		"ent_amb_generic_smolder_lrg",
		"ent_amb_ghost_train_steam",
		"ent_amb_gutter_drips",
		"ent_amb_gutter_splash",
		"ent_amb_hay_pile_debris",
		"ent_amb_haybale_debris",
		"ent_amb_haystack_debris",
		"ent_amb_hog_blood",
		"ent_amb_icicle_drip",
		"ent_amb_insect_bee_swarm",
		"ent_amb_insect_bees",
		"ent_amb_insect_butterfly_swarm2",
		"ent_amb_insect_butterfly_swarm3",
		"ent_amb_insect_butterfly_swarm4",
		"ent_amb_insect_butterfly_swarm5",
		"ent_amb_insect_butterflys_swarm",
		"ent_amb_insect_cockroaches",
		"ent_amb_insect_cockroaches_int",
		"ent_amb_insect_dragonfly_swarm",
		"ent_amb_insect_firefly_swarm",
		"ent_amb_insect_fly_swarm",
		"ent_amb_insect_fly_swarm_horse",
		"ent_amb_insect_fly_swarm_outhouse",
		"ent_amb_insect_fly_swarm_shit",
		"ent_amb_insect_fly_swarm_shit_tracking",
		"ent_amb_insect_grasshopper",
		"ent_amb_insect_maggots",
		"ent_amb_insect_moths_night",
		"ent_amb_insect_moths_night_window",
		"ent_amb_insect_moths_swarm",
		"ent_amb_insect_moths_swarm_lrg",
		"ent_amb_insect_nat_swarm",
		"ent_amb_insect_plane",
		"ent_amb_insect_swamp_flies",
		"ent_amb_insect_swarm",
		"ent_amb_insect_water_bugs",
		"ent_amb_int_fireplace",
		"ent_amb_int_fireplace_win1",
		"ent_amb_int_smoke_lingering",
		"ent_amb_interior_show_fire",
		"ent_amb_light_message_fog",
		"ent_amb_maggots_bodyPartHead02",
		"ent_amb_maggots_boneSkeleton02x",
		"ent_amb_maggots_carcassCow01",
		"ent_amb_maggots_carcassHorse01x",
		"ent_amb_maggots_deadPokerPlayer01x",
		"ent_amb_maggots_s_abe_corpse01",
		"ent_amb_match_flame",
		"ent_amb_mountain_cloud_01",
		"ent_amb_mountain_cloud_02",
		"ent_amb_oil_drips_med",
		"ent_amb_ped_fish_ripples",
		"ent_amb_pollen",
		"ent_amb_rapid_area_spray",
		"ent_amb_rapid_area_spray_hvy",
		"ent_amb_rapid_dir_splash",
		"ent_amb_rapid_dir_splash_light",
		"ent_amb_rapid_dir_splash_long",
		"ent_amb_rapid_dir_splash_short",
		"ent_amb_rapid_dir_splash_wide",
		"ent_amb_rapid_dir_spray",
		"ent_amb_rapid_rock_drips",
		"ent_amb_river_mist_gen",
		"ent_amb_river_rock_splash",
		"ent_amb_river_splash_gen",
		"ent_amb_robot_bulb",
		"ent_amb_robot_smoke",
		"ent_amb_robot_sparks",
		"ent_amb_rolling_boulder_dust",
		"ent_amb_room_haze",
		"ent_amb_sde_smokegroup_1",
		"ent_amb_sde_smokegroup_2",
		"ent_amb_sde_smokegroup_3",
		"ent_amb_sde_smokegroup_4",
		"ent_amb_sewer_drips_lg",
		"ent_amb_sewer_drips_med",
		"ent_amb_sewer_drips_sm",
		"ent_amb_shit_drip",
		"ent_amb_slaughter_sewer_discharge",
		"ent_amb_smoke_cabin",
		"ent_amb_smoke_cabin_distance",
		"ent_amb_smoke_chimney",
		"ent_amb_smoke_chimney_long",
		"ent_amb_smoke_chimney_var_01",
		"ent_amb_smoke_chimney_win1",
		"ent_amb_smoke_factory",
		"ent_amb_smoke_factory_exhaust",
		"ent_amb_smoke_factory_exhaust_sma",
		"ent_amb_smoke_factory_feed",
		"ent_amb_smoke_factory_interior",
		"ent_amb_smoke_factory_sma",
		"ent_amb_smoke_mine",
		"ent_amb_smoke_moon_still",
		"ent_amb_smoke_pipe_s",
		"ent_amb_smoke_pipe_spread",
		"ent_amb_smoke_pipe_spread_var_01",
		"ent_amb_smoke_smolder",
		"ent_amb_smoke_stack_l_connector",
		"ent_amb_smoke_stack_l_mainstream",
		"ent_amb_smoke_stack_m_connector",
		"ent_amb_smoke_stack_m_mainstream",
		"ent_amb_smoke_stack_m_wind",
		"ent_amb_smoke_stack_s_scatter",
		"ent_amb_smoke_teepee_high",
		"ent_amb_smoke_teepee_low",
		"ent_amb_snow_drop",
		"ent_amb_snow_falling_dust_debris",
		"ent_amb_snow_mist_base",
		"ent_amb_snow_mist_upper",
		"ent_amb_snow_mountain_drifts",
		"ent_amb_snow_mountain_drifts_close",
		"ent_amb_snow_mountain_drifts_swirl",
		"ent_amb_snow_roof_drifts",
		"ent_amb_spring_bubbles",
		"ent_amb_stage_light_smoke",
		"ent_amb_steam_boat_engine",
		"ent_amb_steam_compost_piles",
		"ent_amb_steam_donkey_main",
		"ent_amb_steam_donkey_pipes",
		"ent_amb_steam_donkey_vent",
		"ent_amb_steam_geyser",
		"ent_amb_steam_pipe_hvy",
		"ent_amb_steam_pipe_lgt",
		"ent_amb_steam_piston",
		"ent_amb_steam_pot",
		"ent_amb_steam_vent_open_hvy",
		"ent_amb_steam_vent_open_lgt",
		"ent_amb_steam_vent_rnd_hvy",
		"ent_amb_steam_vent_round",
		"ent_amb_stove_fire_sml",
		"ent_amb_stove_pipe_smoke",
		"ent_amb_stove_pipe_smoke_darker",
		"ent_amb_swing_trap_dust",
		"ent_amb_tadpole_swarm",
		"ent_amb_tar_bubbles",
		"ent_amb_torch_fire",
		"ent_amb_toy_boat_idle_smoke",
		"ent_amb_trn4_train_smoke",
		"ent_amb_trolley_hook_sparks",
		"ent_amb_trop_fish_swarm_angel",
		"ent_amb_trop_fish_swarm_col",
		"ent_amb_trop_fish_swarm_lil",
		"ent_amb_washtub_lather",
		"ent_amb_water_cave_drips_mesh",
		"ent_amb_water_drips_cave_col",
		"ent_amb_water_drips_cave_lg",
		"ent_amb_water_drips_cave_med",
		"ent_amb_water_drips_cave_sm",
		"ent_amb_water_drips_hydro",
		"ent_amb_water_drips_lg",
		"ent_amb_water_drips_med",
		"ent_amb_water_drips_sm",
		"ent_amb_water_drips_sm_sound",
		"ent_amb_water_drips_trees",
		"ent_amb_water_icicle_drips_sm",
		"ent_amb_water_roof_drips_lg",
		"ent_amb_water_roof_drips_med",
		"ent_amb_water_roof_drips_sm",
		"ent_amb_water_roof_pour",
		"ent_amb_water_roof_pour_long",
		"ent_amb_water_roof_rain_mesh",
		"ent_amb_wf_bw",
		"ent_amb_wf_close_spray",
		"ent_amb_wf_cum_01",
		"ent_amb_wf_dak_bb_01",
		"ent_amb_wf_dak_bb_02",
		"ent_amb_wf_dak_gp_03",
		"ent_amb_wf_dak_gp_04",
		"ent_amb_wf_dak_gp_05",
		"ent_amb_wf_dak_gp_06",
		"ent_amb_wf_dak_gp_v2_01",
		"ent_amb_wf_dak_gp_v2_02",
		"ent_amb_wf_dak_gp_v2_03",
		"ent_amb_wf_dak_up_01",
		"ent_amb_wf_dak_up_02",
		"ent_amb_wf_dak_up_03",
		"ent_amb_wf_decal",
		"ent_amb_wf_ely_01",
		"ent_amb_wf_ely_splash",
		"ent_amb_wf_lens",
		"ent_amb_wf_lmr_mist",
		"ent_amb_wf_man",
		"ent_amb_wf_man_narrow",
		"ent_amb_wf_mist_lg",
		"ent_amb_wf_mist_md",
		"ent_amb_wf_proto_01",
		"ent_amb_wf_proto_01_larger",
		"ent_amb_wf_proto_02_cloud",
		"ent_amb_wf_proto_02_cloud_va_wide",
		"ent_amb_wf_proto_02_cloud_var",
		"ent_amb_wf_proto_02_spray",
		"ent_amb_wf_proto_fog",
		"ent_amb_wf_soak",
		"ent_amb_wf_splash_base",
		"ent_amb_wf_splash_base_med",
		"ent_amb_wf_splash_base_sm",
		"ent_amb_wf_splash_cloud",
		"ent_amb_wf_splash_lg",
		"ent_amb_wf_splash_md",
		"ent_amb_wf_splash_sm",
		"ent_amb_wf_top_bits",
		"ent_amb_wf_whitewater",
		"ent_amb_wfall_strwb_base",
		"ent_amb_wfall_strwb_top",
		"ent_amb_wind_grass",
		"ent_amb_wind_grass_dir",
		"ent_amb_wind_hay",
		"ent_amb_wind_hay_dir",
		"ent_amb_wind_leaves",
		"ent_amb_wind_leaves_dir",
		"ent_amb_wind_leaves_swirl",
		"ent_amb_wind_litter",
		"ent_amb_wind_litter_dir",
		"ent_amb_wind_litter_dust",
		"ent_amb_wind_litter_dust_dir",
		"ent_amb_wind_litter_dust_swirl",
		"ent_amb_wind_litter_swirl",
		"ent_amb_wind_petal_tint_dir",
		"ent_amb_wind_rand_litter",
		"ent_amb_wind_snow_bendleft",
		"ent_amb_wind_snow_bendright",
		"ent_amb_wind_snow_drifts",
		"ent_amb_wind_snow_ground",
		"ent_amb_wind_snowfall",
		"ent_amb_wind_tree_leaves",
		"ent_amb_wwheel_strwb_base",
		"ent_amb_wwheel_strwb_top",
		"env_air_debris",
		"env_ash",
		"env_cloud",
		"env_desert_ground_dust",
		"env_dust_motes",
		"env_embers",
		"env_firefly_swarm",
		"env_firesmoke",
		"env_flies",
		"env_fog",
		"env_interior_dusty",
		"env_interiorsmoke",
		"env_pollen",
		"env_rain_mist",
		"env_sandstorm",
		"env_smoke",
		"env_swamp_flies",
		"env_wind_debris_city",
		"env_wind_debris_city_slum",
		"env_wind_debris_countryside",
		"env_wind_debris_desert",
		"env_wind_debris_industrial_ash",
		"env_wind_debris_mountain",
		"env_wind_debris_woodland",
		"env_wind_debris_woodland_pine",
		"env_wind_mountain_snow",
		"exp_grn_cloud",
		"exp_poison_bottle",
		"exp_sht_flame",
		"exp_sht_steam",
		"exp_water_spout",
		"fire_gunpowder_trail",
		"fire_map",
		"fire_oil_pool",
		"fire_oil_trail",
		"fire_ped_body",
		"fire_ped_limb",
		"fire_petrol_pool",
		"fire_petrol_script",
		"fire_petrol_trail",
		"fire_petroltank_car",
		"fire_spread_generic",
		"fire_spread_generic_obj",
		"fire_spread_generic_smoulder_loop",
		"fire_spread_generic_smoulder_obj",
		"fire_wheel",
		"fire_wrecked_boat",
		"fire_wrecked_car",
		"fire_wrecked_car_vent",
		"fire_wrecked_hot_air_balloon",
		"fire_wrecked_train",
		"liquid_leak_blood",
		"liquid_leak_flour",
		"liquid_leak_grain",
		"liquid_leak_gunpowder",
		"liquid_leak_kerosene",
		"liquid_leak_moonshine",
		"liquid_leak_oil",
		"liquid_leak_petrol",
		"liquid_leak_sand",
		"liquid_leak_sugar",
		"liquid_leak_water",
		"mtl_debris_dirt_light",
		"mtl_debris_dirt_medium",
		"mtl_debris_gravel_dirt_light",
		"mtl_debris_gravel_dirt_medium",
		"mtl_debris_gravel_heavy",
		"mtl_debris_gravel_light",
		"mtl_debris_gravel_medium",
		"mtl_debris_sand",
		"mtl_debris_snow_loose",
		"mtl_debris_woodchips",
		"mtl_disturb_dust",
		"mtl_disturb_grass",
		"mtl_disturb_gravel",
		"mtl_disturb_leaves",
		"mtl_disturb_mud",
		"mtl_disturb_snow_loose",
		"mtl_disturb_woodchips",
		"muz_moonshine",
		"muz_smoking_barrel",
		"muz_smoking_barrel_cannon",
		"muz_smoking_barrel_rifle",
		"muz_smoking_barrel_shotgun",
		"ped_bear_mouth_froth",
		"ped_blood_drips",
		"ped_blood_pool_water",
		"ped_body_heat_haze_horse",
		"ped_breath_fish_bubbles",
		"ped_breath_scuba",
		"ped_breath_water",
		"ped_corpse_flies",
		"ped_dog_mouth_froth",
		"ped_foot_ash_horse_scuff",
		"ped_foot_ash_muddy_horse_scuff",
		"ped_foot_dirt_dry_horse_scuff",
		"ped_foot_dirt_muddy_horse_scuff",
		"ped_foot_dust_horse_scuff",
		"ped_foot_dust_scuff",
		"ped_foot_gravel_dirt_horse_scuff",
		"ped_foot_gravel_grass_horse_scuff",
		"ped_foot_gravel_horse_scuff",
		"ped_foot_gravel_muddy_horse_scuff",
		"ped_foot_gravel_scuff",
		"ped_foot_hay_scuff",
		"ped_foot_leaves_ficus_horse_scuff",
		"ped_foot_leaves_horse_scuff",
		"ped_foot_leaves_maple_horse_scuff",
		"ped_foot_leaves_oak_horse_scuff",
		"ped_foot_leaves_wet_ficus_horse_scuff",
		"ped_foot_leaves_wet_horse_scuff",
		"ped_foot_leaves_wet_maple_horse_scuff",
		"ped_foot_leaves_wet_oak_horse_scuff",
		"ped_foot_mud_soft_horse_scuff",
		"ped_foot_powder_horse_scuff",
		"ped_foot_sand_wet_horse_scuff",
		"ped_foot_snow_horse_scuff",
		"ped_foot_twigs_horse_scuff",
		"ped_foot_twigs_wet_horse_scuff",
		"ped_foot_water_horse_scuff",
		"ped_grd_disturb_dust",
		"ped_grd_disturb_dust_ash_horse_light",
		"ped_grd_disturb_dust_dirt_horse_heavy",
		"ped_grd_disturb_dust_dirt_horse_light",
		"ped_grd_disturb_dust_dirt_horse_medium",
		"ped_grd_disturb_dust_heavy",
		"ped_grd_disturb_mud_underwater",
		"ped_grd_disturb_snow",
		"ped_grd_disturb_snow_horse",
		"ped_grd_disturb_snow_loose",
		"ped_grd_disturb_snow_loose_horse",
		"ped_hatbrim_drip",
		"ped_horse_flaming_hoof",
		"ped_horse_mouth_froth",
		"ped_underwater_disturb_dirt",
		"ped_underwater_disturb_sand",
		"ped_underwater_trails",
		"ped_underwater_trails_horse",
		"ped_wade_mud",
		"ped_wade_mud_watery",
		"ped_wade_snow",
		"ped_wade_snow_horse",
		"ped_wade_snow_horse_mp",
		"ped_wade_snow_mp",
		"ped_wade_tar",
		"ped_wash_blood",
		"ped_wash_mud",
		"ped_water_drips",
		"ped_water_drips_horse",
		"ped_waterfall_collision",
		"proj_arrow_fire",
		"proj_arrow_fire_trail",
		"proj_arrow_trail",
		"proj_arrow_trail_custom",
		"proj_cannon_trail",
		"proj_disturb_dust",
		"proj_dynamite_fuse",
		"proj_dynamite_trail",
		"proj_molotov_flame",
		"proj_molotov_trail",
		"scr_winter1_barn_door_snow",
		"scrape_ash",
		"scrape_blood",
		"scrape_clay",
		"scrape_concrete",
		"scrape_dirt_dry",
		"scrape_dust",
		"scrape_glass",
		"scrape_gravel",
		"scrape_ice",
		"scrape_manure",
		"scrape_metal",
		"scrape_moss",
		"scrape_mud",
		"scrape_mud_soft",
		"scrape_mud_underwater",
		"scrape_ped_foot_mud_soft",
		"scrape_ped_grass",
		"scrape_ped_leaves",
		"scrape_ped_leaves_ficus",
		"scrape_ped_leaves_maple",
		"scrape_ped_leaves_oak",
		"scrape_ped_limb_mud_soft",
		"scrape_ped_snow",
		"scrape_ped_torso_mud_soft",
		"scrape_sand",
		"scrape_sand_wet",
		"scrape_slush",
		"scrape_snow",
		"scrape_twigs",
		"scrape_wood",
		"trail_splash_blood",
		"trail_splash_flour",
		"trail_splash_grain",
		"trail_splash_gunpowder",
		"trail_splash_oil",
		"trail_splash_petrol",
		"trail_splash_sand",
		"trail_splash_sugar",
		"trail_splash_water",
		"veg_disturb_flower_petals",
		"veg_disturb_flower_pollen",
		"veg_disturb_generic",
		"veh_air_debris",
		"veh_candle_flame",
		"veh_exhaust_boat",
		"veh_exhaust_boat_steam_large",
		"veh_exhaust_boat_steam_med",
		"veh_exhaust_boat_steam_med_turbine",
		"veh_exhaust_boat_steam_sma",
		"veh_exhaust_car",
		"veh_exhaust_car_steam",
		"veh_exhaust_hot_air_balloon",
		"veh_exhaust_misfire",
		"veh_exhaust_start",
		"veh_exhaust_train_smoke",
		"veh_exhaust_train_smoke_high",
		"veh_exhaust_train_smoke_low",
		"veh_exhaust_train_steam",
		"veh_ghost_train_furnace_fire",
		"veh_light_red_trail",
		"veh_trailer_petrol_spray",
		"veh_train_drain_cock_steam",
		"veh_train_furnace_fire",
		"veh_train_grd_disturb_dust_dirt",
		"veh_train_grd_disturb_dust_leaves",
		"veh_train_grd_disturb_dust_snow",
		"veh_train_piston_gland_steam",
		"veh_train_refrigerator_cold_air",
		"veh_train_room_cold_air",
		"veh_train_sparks",
		"veh_train_sparks_tender",
		"veh_train_whistle",
		"veh_vent_boat",
		"water_boat_bow",
		"water_boat_leak",
		"water_boat_lod",
		"water_boat_lod_bow",
		"water_boat_lod_side",
		"water_boat_oar_wade",
		"water_boat_prop",
		"water_boat_rev",
		"water_boat_steam_horseboat_bow",
		"water_boat_steam_horseboat_rev",
		"water_boat_steam_horseboat_wash",
		"water_boat_steam_keelboat_bow",
		"water_boat_steam_med_bow",
		"water_boat_steam_med_prop",
		"water_boat_steam_med_rev",
		"water_boat_steam_med_wash",
		"water_boat_steam_nbdguama_wash",
		"water_boat_steam_sma_bow",
		"water_boat_steam_sma_prop",
		"water_boat_steam_sma_rev",
		"water_boat_steam_sma_wash",
		"water_boat_steam_tugboat_bow",
		"water_boat_steam_tugboat_rev",
		"water_boat_steam_tugboat_wash",
		"water_boat_steam_turbine_bow",
		"water_boat_steam_turbine_rev",
		"water_boat_steam_turbine_wash",
		"water_boat_wash",
		"water_canoe_bow",
		"water_canoe_oar_wade",
		"water_canoe_rev",
		"water_canoe_wash",
		"water_pirogue_bow",
		"water_pirogue_rev",
		"water_pirogue_wash",
		"water_rowboat_bow",
		"water_rowboat_rev",
		"water_rowboat_swamp_bow",
		"water_rowboat_swamp_wash",
		"water_rowboat_wash",
		"water_splash_gator_wade",
		"water_splash_obj_trail",
		"water_splash_obj_wade",
		"water_splash_ped_duck_wade",
		"water_splash_ped_wade",
		"water_splash_ped_wade_human",
		"water_splash_ped_wade_lod",
		"water_splash_ped_wade_lower",
		"water_splash_ped_wade_lower_bear",
		"water_splash_ped_wade_lower_deer",
		"water_splash_ped_wade_lower_horse",
		"water_splash_rope_wade",
		"water_splash_veh_trail",
		"water_splash_veh_wade",
		"water_splash_wheel_cart",
		"weap_torch_fire_trail",
		"wheel_disp_blood",
		"wheel_disp_dirt_dry",
		"wheel_disp_dirt_wet",
		"wheel_disp_flour",
		"wheel_disp_generic_underwater",
		"wheel_disp_generic_wet",
		"wheel_disp_grass",
		"wheel_disp_grass_wet",
		"wheel_disp_gravel",
		"wheel_disp_gravel_wet",
		"wheel_disp_ice",
		"wheel_disp_leaves",
		"wheel_disp_leaves_wet",
		"wheel_disp_lod_dust_light",
		"wheel_disp_lod_dust_medium",
		"wheel_disp_lod_dust_sand_medium",
		"wheel_disp_mud_liquid",
		"wheel_disp_mud_soft",
		"wheel_disp_oil",
		"wheel_disp_petrol",
		"wheel_disp_sand",
		"wheel_disp_slush",
		"wheel_disp_snow",
		"wheel_disp_tar",
		"wheel_disp_water",
		"wheel_disp_water_puddle",
		"wheel_fric_concrete",
		"wheel_fric_dirt_dry",
		"wheel_fric_dirt_wet",
		"wheel_fric_flour",
		"wheel_fric_generic_underwater",
		"wheel_fric_generic_wet",
		"wheel_fric_grass_dry",
		"wheel_fric_gravel_dry",
		"wheel_fric_gravel_wet",
		"wheel_fric_ice",
		"wheel_fric_leaves_dry",
		"wheel_fric_mud_liquid",
		"wheel_fric_mud_soft",
		"wheel_fric_sand_dry",
		"wheel_fric_snow",
		"wheel_fric_tar",
		"wheel_spray_mud_liquid",
		"wheel_spray_mud_soft",
		"wheel_spray_snow",
		"wheel_spray_water",
		"wpn_scope_glint",
	},
	["scr_shows_fire_dancer"] = {
		"scr_fire_dancer_disturb",
	},
	["scr_fire_manager"] = {
		"ent_amb_campfire_dynamic",
		"ent_amb_insect_water_flies",
		"ent_anim_fire_tend_embers",
	},
	["anm_blood"] = {
		"ent_anim_blood_drips",
		"ent_anim_blood_spurt",
		"ent_anim_blood_spurt_cougar",
		"ent_anim_mouth_blood",
		"ent_anim_stab_blood_drips",
		"ent_anim_throat_blood_deer",
		"ent_anim_throat_slit_bear",
		"ent_anim_wolf_blood_drip",
	},
	["scr_train_robbery4"] = {
		"scr_trainrob4_train_carriage_fire",
		"scr_trn4_ground_plume",
		"scr_trn4_train_const_smoke",
		"scr_trn4_train_slide",
		"scr_trn4_train_smoke_loop",
	},
	["anm_core"] = {
		"ent_anim_boat_smoke",
		"ent_anim_campfire_stomp",
		"ent_anim_muz_smoking_barrel",
		"ent_anim_ped_wade_snow",
		"ent_anim_train_exhaust_smoke",
		"ent_anim_vial_revive",
	},
	["scr_net_moon_bartending"] = {
		"scr_net_moonshine_pour_bar",
	},
	["scr_net_koth"] = {
		"scr_net_koth_smoke_factory",
	},
	["anm_weapons"] = {
		"ent_anim_dynamite_fuse",
		"ent_anim_gun_linger",
		"ent_anim_molotov_flame",
		"ent_anim_muz_gatling",
		"ent_anim_muz_gatling_close",
		"ent_anim_proj_key_trail",
	},
	["scr_adv_sok"] = {
		"scr_adv_sok_torch",
		"scr_adv_sok_torch_horseback",
		"scr_adv_sok_torchsmoke",
	},
	["scr_annesburg"] = {
		"blood_stone_crusher_stream",
	},
	["scr_trelawny2"] = {
		"scr_trl2_train_steam",
	},
	["scr_mg_fishing"] = {
		"scr_mg_fishing_drips",
	},
	["anm_brt"] = {
		"ent_anim_moonshine_pour",
	},
	["cut_fud1"] = {
		"CS_Fud1_Boat_scrape_sand_wet",
	},
	["scr_arch_jameson3"] = {
		"blood_stone_crusher_stream",
	},
	["amb_lights"] = {
		"amb_arc_lamp_emit",
		"amb_bulb_g_01",
		"amb_bulb_g_01_frosted",
		"amb_bulb_g_01_frosted_skin",
		"amb_bulb_g_01_lantern",
		"amb_bulb_g_01_sign",
		"amb_bulb_g_01_sign_frosted",
		"amb_bulb_g_01_skin",
		"amb_bulb_g_01_xmas_sign",
		"amb_bulb_g_01_xmas_sign_frosted",
		"amb_candle_flame_emit",
		"amb_gas_flame_emit",
		"amb_gas_flame_emit_narrow",
		"amb_lantern_flame_emit",
		"amb_miner_hat_flame_emit",
	},
	["scr_net_beat_gator_hunters"] = {
		"scr_net_beat_gator_blood_water",
		"scr_net_beat_gator_splash",
	},
	["scr_odr1"] = {
		"scr_od1_camp_smoke",
	},
	["scr_beat_treasure_hunter"] = {
		"scr_event_glint",
	},
	["anm_mud"] = {
		"ent_anim_shaking_dust",
		"ent_anim_shaking_gravel",
	},
	["scr_net_impromptu_race"] = {
		"scr_net_imp_race_smoke",
	},
	["anm_fire_dancers"] = {
		"ent_anim_fire_breathe_loop",
		"ent_anim_fire_dancer_belt",
		"ent_anim_fire_dancer_trail",
	},
	["anm_gator"] = {
		"ent_anim_gator_ambush",
		"ent_anim_gator_attack_ripple",
		"ent_anim_gator_blood",
		"ent_anim_gator_bubbles_underwater",
		"ent_anim_gator_grapple",
		"ent_anim_gator_ripples",
		"ent_anim_gator_splash",
	},
	["scr_fussar2"] = {
		"scr_fus2_trap_rope_dust",
	},
	["scr_murderbeat"] = {
		"scr_murder_bleeding",
	},
	["anm_shaving"] = {
		"ent_anim_ped_razor_fling",
		"ent_anim_ped_shave_brush",
		"ent_anim_ped_shave_face",
	},
	["scr_vignette_javier_5"] = {
		"ent_amb_rainbow_lg",
	},
	["anm_impacts"] = {
		"ent_anim_steam_linger_smoke",
		"ent_anim_wheel_sand_mud",
	},
	["scr_odd_fellows"] = {
		"scr_river5_magician_smoke_loop",
	},
	["scr_native_son1"] = {
		"scr_ntvs1_water_rush",
	},
	["scr_mob4"] = {
		"scr_blood_pool_water_trail",
		"scr_mob4_gator_ripple",
		"scr_mob4_leg_blood",
	},
	["scr_braithwaites1"] = {
		"ent_amb_cig_smoke_linger",
		"scr_brt1_bar_mg_liq_pour",
		"scr_brt1_bar_mg_liq_pour_splash",
	},
	["anm_ind"] = {
		"ent_anim_ind_firework",
		"ent_anim_ind_firework_lights",
		"ent_anim_ind_firework_lights_bright",
	},
	["scr_impromptu_race"] = {
		"scr_imp_race_smoke",
	},
	["anm_fire"] = {
		"ent_anim_campfire_dynamic",
		"ent_anim_candle_flame",
		"ent_anim_candle_smoke",
		"ent_anim_fire_generic_win",
		"ent_anim_fire_logs",
		"ent_anim_fire_spread_generic",
		"ent_anim_fire_tend_embers",
		"ent_anim_generic_fire_smoke_plume",
		"ent_anim_gua1_boat_fire",
		"ent_anim_lantern_fire",
		"ent_anim_lantern_fire_trn4",
		"ent_anim_ped_fire",
		"ent_anim_rslvc_burn_book",
		"ent_anim_rslvc_burn_book_haze",
		"ent_anim_sklr_lighter_flame",
		"ent_anim_stove_fire",
		"ent_anim_stove_heat_haze",
	},
	["scr_net_fire_smoke"] = {
		"ent_amb_generic_fire_field",
		"ent_amb_generic_fire_field_nosmoke",
		"ent_amb_generic_fire_field_smoke",
		"ent_amb_generic_fire_smoke_plume",
		"ent_amb_moo_crop_fire",
		"env_embers",
		"env_smoke",
		"scr_brt2_firesmoke_field",
		"scr_mp_collect_campfire_smoke",
		"scr_mp_collect_pickup_highlight",
		"scr_mp_item_pickup_highlight",
	},
	["scr_adv_hp"] = {
		"scr_adv_hp_helmet_fire",
	},
	["anm_water_panning"] = {
		"ent_anim_water_panning",
		"ent_anim_water_panning_bucket_drips",
		"ent_anim_water_panning_bucket_pour",
		"ent_anim_water_panning_nugget_drips",
	},
	["scr_short_update"] = {
		"scr_campfire_smoke_distance",
	},
	["scr_finale2"] = {
		"scr_fin2_cleet_drag_dust",
	},
	["eagle_eye"] = {
		"eagle_eye_bait",
		"eagle_eye_clue",
		"eagle_eye_clue_animal_transform",
		"eagle_eye_entity",
		"eagle_eye_lootable_plant",
		"eagle_eye_trail",
		"eagle_eye_wind",
		"eagle_eye_wind_balloon",
	},
	["anm_nbd"] = {
		"ent_anim_nbd_guama_bow",
		"ent_anim_nbd_guama_bow_left",
		"ent_anim_nbd_guama_prop",
		"ent_anim_nbd_guama_steam",
		"ent_anim_nbd_guama_wash_left",
		"ent_anim_nbd_guama_wash_right",
	},
	["anm_human_sick_pee"] = {
		"ent_anim_human_puke",
		"ent_anim_peeing",
	},
	["scr_braithwaites2"] = {
		"ent_amb_falling_embers",
		"ent_amb_generic_fire_field",
		"ent_amb_generic_fire_field_glow",
		"ent_amb_generic_fire_field_nosmoke",
		"ent_amb_generic_fire_field_smoke",
		"ent_amb_generic_fire_up",
		"env_embers",
		"scr_brt2_fire_roof",
		"scr_brt2_fire_win",
		"scr_brt2_firesmoke",
		"scr_brt2_firesmoke_barn",
		"scr_brt2_firesmoke_field",
	},
	["scr_winter4"] = {
		"proj_dynamite_trail",
		"scr_winter4_horse_disturb_dust",
	},
	["scr_beat_murder_for_hire"] = {
		"scr_beat_mur_blood_spray",
	},
	["scr_smuggler2"] = {
		"proj_cannon_trail",
	},
	["scr_beat_animal_mauling"] = {
		"scr_beat_anml_blood_spray",
	},
	["anm_smoking"] = {
		"cs_cig_smoke",
		"cs_cig_smoke_inhale",
		"ent_anim_cig_smoke",
		"ent_anim_cig_smoke_cigar",
		"ent_anim_cig_smoke_cigar_ember",
		"ent_anim_cig_smoke_ember",
		"ent_anim_cig_smoke_preload",
		"ent_anim_cig_smoke_trail",
		"ent_anim_cig_smoke_walking",
		"ent_anim_matchstick_flame",
		"ent_anim_rccig_linger_smoke",
	},
	["des_gry1_mnshine_exp"] = {
		"ent_ray_gry1_water_splash",
	},
	["markers_core"] = {
		"ent_amb_net_race_fire",
		"ent_amb_net_race_smoke",
		"ent_amb_net_race_smoke_target",
		"scr_net_race_arrow",
	},
	["scr_adv_ova_hunter"] = {
		"scr_hunter_cloak_haze_head",
		"scr_hunter_cloak_haze_limb",
		"scr_hunter_cloak_haze_torso",
	},
	["anm_chamberpot"] = {
		"ent_anim_chamberpot_toss",
		"ent_anim_chamberpot_toss_short",
	},
	["scr_rcm_native2"] = {
		"scr_natv3_fire_oil_field",
		"scr_natv3_fire_oil_plume",
		"scr_natv3_generic_fire",
	},
	["scr_adv_ph"] = {
		"scr_adv_ph_glow_plinth",
		"scr_adv_ph_glow_bag",
		"scr_adv_ph_glow_bag_rear",
		"scr_adv_ph_glow_head",
		"scr_adv_ph_glow_limb",
		"scr_adv_ph_glow_plinth",
		"scr_adv_ph_glow_torso",
	},
	["scr_odr3"] = {
		"scr_odr3_blood_spurt",
		"scr_odr3_surgery_heat",
	},
	["scr_deadeye"] = {
		"scr_de_conviction_weapon_glow",
		"scr_de_focus_tracer",
		"scr_de_recuperate_wisps",
		"scr_de_slippery_haze_head",
		"scr_de_slippery_haze_limb",
		"scr_de_slippery_haze_torso",
		"scr_de_steady_smoke_torso",
		"scr_de_watch_wisps",
	},
	["scr_demo1"] = {
		"proj_dynamite_trail",
	},
	["scr_net_fme"] = {
		"scr_fme_corpse_fly_swarm",
	},
	["anm_gang2"] = {
		"ent_anim_gng2_balloon_leaves",
		"ent_anim_gng2_balloon_mud_scrape",
		"ent_anim_gng2_balloon_wtr_spl",
	},
	["scr_beat_bear_trap"] = {
		"scr_beat_bear_blood_spray",
	},
	["scr_ind1"] = {
		"scr_ind1_firework",
		"scr_ind1_firework_lights",
	},
	["scr_net_dynamite"] = {
		"proj_dynamite_trail",
	},
	["scr_train_robbery3"] = {
		"scr_trn3_water_splash_surface",
	},
	["scr_trelawny1"] = {
		"scr_trelawny1_smoke",
	},
	["scr_net_race_checkpoints"] = {
		"scr_mp_item_pickup_highlight",
		"scr_net_race_slipstream",
	},
	["scr_vantage_point"] = {
		"scr_event_glint",
	},
	["scr_fussar1"] = {
		"scr_fus1_lantern_fire",
		"scr_fussar1_cave_steam",
		"scr_fussar1_dust_cloud",
		"scr_fussar1_dust_fog",
		"scr_fussar1_dusty_interior",
		"scr_fussar1_sb_short",
		"trail_splash_oil",
	},
	["scr_braithwaites3"] = {
		"scr_braithw3_curtain_fire_01",
		"scr_braithw3_hall_smoke",
		"scr_braithw3_mansion_fire_crawling",
		"scr_braithw3_mansion_fire_under",
		"scr_braithw3_mansion_fire_win1",
		"scr_braithw3_mansion_fire_win2",
		"scr_braithw3_room_ash",
		"scr_braithw3_room_embers",
		"scr_braithw3_room_smoke_01",
	},
}
